### ISSUE TITLE
Any plan A Google Protobuf implementation for Lisp Flavoured Erlang (LFE)

### ISSUE THREAD

**Issue by longde123** [tomas-abrahamsson/gpb#100]
gpb_codegen_lfe.erl   port lfe erlang

?

**Comment by tomas-abrahamsson** [comment]
Are the generated Erlang encoding/decoding functions usable from lfe as is, maybe with the `maps` option? The generated introspection functions might also be useful, please take a look at them. I think that's what the Elixir binding uses, together with the data-driven auxiliary encoder/decoder in the `gpb` module. Is this sufficient?

**Comment by tomas-abrahamsson** [comment]
I'll close this, if you have anything in mind, just re-open
