### ISSUE TITLE
Type default for maps is wrong when mapsfield_as_maps is set

### ISSUE THREAD

**Issue by tsloughter** [tomas-abrahamsson/gpb#101]
https://github.com/tomas-abrahamsson/gpb/blob/master/src/gpb.erl#L1071 should be setting the field to `#{}` if proto maps are to be treated as Erlang maps. I don't see a good way to get that information to the function so I don't have a PR at this time.

**Comment by tsloughter** [comment]
Nevermind seems it just needs the change in https://github.com/tomas-abrahamsson/gpb/pull/102

**Comment by tomas-abrahamsson** [comment]
I'll close this then, since the #102 is in 3.26.7
