### ISSUE TITLE
Support for Custom Options

### ISSUE THREAD

**Issue by hayesgm** [tomas-abrahamsson/gpb#107]
As per the [Protobuf spec](https://developers.google.com/protocol-buffers/docs/proto#options) on Custom Options, the spec includes:

> Protocol Buffers even allow you to define and use your own options.

To specify the option, you must wrap it in parenthesis, as per:

> When we then use the option, the option name must be enclosed in parentheses to indicate that it is an extension.

However, when I try to parse an extension with `gpb`, I am getting the following error:

Protobuf:

```protobuf
import "google/protobuf/descriptor.proto";

extend google.protobuf.MessageOptions {
  optional string my_option = 51234;
}

message MyMessage {
  option (my_option) = "Hello world!";
}
```

Error:

```elixir
(Protobuf.Parser.ParserError) 11('syntax error before: ', '\'(\'')
    lib/exprotobuf/parser.ex:68: Protobuf.Parser.parse!/2
    lib/exprotobuf/parser.ex:10: anonymous fn/3 in Protobuf.Parser.parse_files!/2
    (elixir) lib/enum.ex:1755: Enum."-reduce/3-lists^foldl/2-0-"/3
    lib/exprotobuf/parser.ex:8: Protobuf.Parser.parse_files!/2
    lib/exprotobuf.ex:68: Protobuf.parse/2
    expanding macro: Protobuf.__using__/1
    lib/job_service/defs.ex:2: Defs (module)
    (elixir) expanding macro: Kernel.use/2
    lib/job_service/defs.ex:2: Defs (module)
    (elixir) lib/kernel/parallel_compiler.ex:117: anonymous fn/4 in Kernel.ParallelCompiler.spawn_compilers/1
```

I am parsing this (via [exprotobuf](https://github.com/bitwalker/exprotobuf)), but the issue is due to the parenthesis in the custom option.

Do we have any intension of supporting custom options? Are there any known work-arounds?

**Comment by tomas-abrahamsson** [comment]
Closing this as your #108 was included in 3.27.1. Thanks!
