### ISSUE TITLE
When using maps, message name is not present

### ISSUE THREAD

**Issue by SergejJurecko** [tomas-abrahamsson/gpb#112]
While usually it is not required, sometimes you require it. Especially when working with recursive messages.

Perhaps a configuration option to set message name field to map: -msg_name "msg.name" 
Example map output would then be:

`
#{'msg.name' => m2, i1 => 17}
`

**Comment by tomas-abrahamsson** [comment]
I decided against including the name of the thing into itself, main reason being that neither lists nor tuples in general, contain kind of type name---it's just the value. At some point you always know what type the value is (just as for lists, integers and so on), and if you need to, at that point, you can always make a tuple of it.

**Comment by tomas-abrahamsson** [comment]
In any case, I've made a note to reconsider and maybe implement this some day, but at the moment, it is not top of my prio list.

**Comment by tomas-abrahamsson** [comment]
I'm closing this for now, since I don't think this is going to be implemented any time soon.
