### ISSUE TITLE
Cannot parse proto3 file

### ISSUE THREAD

**Issue by mango009** [tomas-abrahamsson/gpb#113]
It seems protoc-erl cannot parse proto3 file. The proto file:
syntax = "proto3";

message Node {
   string host = 1;
   string container = 2;
   string ros_name = 3;
   int32 port = 4;
 }
 
The error:
proto/aos.proto:1: syntax error before: syntax

**Comment by tomas-abrahamsson** [comment]
Strange, it works out of the box for me, when I copy-pasted your text, even when I added an UTF-8 byte order mark. Maybe you have some kind of invisible character at the beginning of your file? (eg run `od -c < aos.proto` to see the actual bytes of the file) Also, what version of gpb do you use?

**Comment by mango009** [comment]
False alarm. I had an old clone of the repository and did a git pull today. Something might got messed up during the process. I re-clone the repository and everything is fine.
Thanks.

**Comment by tomas-abrahamsson** [comment]
Good thing it got sorted out. Closing issue.
