### ISSUE TITLE
When using maps, fail upon trying to encode message with unknown fields

### ISSUE THREAD

**Issue by g-andrade** [tomas-abrahamsson/gpb#116]
Over the past few months, on my regular usage of gpb, I've been transitioning from records to maps. A pitfall I commonly run into is having a typo in a field name; e.g., let's say we have the following message definition:

```protobuf
message Foo {
    optional int32 bar_value = 1;
}
```

And later on we try encoding the following map using the message type above:

```erlang
Foo = #{ bar => 5 }
```

It will succeed. And the end result can be decoded successfully, simply appearing to miss the bar_value field, which is indeed optional. Dialyzer doesn't complain about it either.

Tracking this sort of bug can be very time consuming, and it was something records saved the user from because there were compile-time checks that failed immediately. What do you think about failing in runtime, upon encoding, in the case of maps?

**Comment by tomas-abrahamsson** [comment]
It sounds very useful. I'm thinking a suitable place for such a check would be in the generated verify functions, would that be ok?

**Comment by g-andrade** [comment]
Sounds great 👍 Thank you.

**Comment by tomas-abrahamsson** [comment]
I will look into it

**Comment by tomas-abrahamsson** [comment]
In 3.27.7, which I've just pushed, the verification checks for extraneous fields in maps. It does so only for `maps_unset_optional = omitted` which was the only case I figure makes sense, since it is only here that misspelled optional fields would otherwise be treated as unset. I'm closing this ticket now, just re-open if there's anything more.

**Comment by g-andrade** [comment]
Perfect! It's working well.
