### ISSUE TITLE
Exception when unable to decode a binary

### ISSUE THREAD

**Issue by tsloughter** [tomas-abrahamsson/gpb#120]
I was wondering if having `decode_msg` be wrapped in a try and throw an exception (or error like verify does) if it fails an acceptable patch? It currently will usually be a case clause failure, making it impossible to know, without manually wrapping every call to a `decode_msg`, it is a failure in decoding a message when caught at a higher level.

**Comment by tomas-abrahamsson** [comment]
Do you mean to be able to tell difference between invalid binary (from protobuf encoding rules point of view) and invalid use of decode_msg (eg called with something not a binary)?

**Comment by tsloughter** [comment]
I was thinking just about binaries. An example being decoding the body of an HTTP request that must be a certain proto message. If the user instead sent either another proto or something entirely different in the body I wanted the failure to propagate up as a clear failure to decode, as opposed to a case clause match failing.

**Comment by tomas-abrahamsson** [comment]
Ok, I see. For the vast majority of the cases, the actual crash details are probably unimportant, but on some occasions I've had use of them, mostly when debugging gpb's own code generation during development. Do you envision that the crash wrapping would be opt in or out, or that it would contain the inner error plus stack trace (in which case, it could probably be always on)?

**Comment by tsloughter** [comment]
I could see it either way. I'd would be happy with it being like the verify option to encode.

**Comment by tomas-abrahamsson** [comment]
Yes, agree option is best way to go. Would you want to take a stab at it or should I? I'm a bit short of time atm so it might be a week or so for me.

**Comment by tsloughter** [comment]
Cool, yea, I'll take a crack at it.

**Comment by tomas-abrahamsson** [comment]
I pushed a proposal to the branch error-on-decoding-failure. It wraps and calls `error({gpb_error,{decoding_failure,Bin,MsgName,Details}}})` in the catch. Is it something like this that you have in mind?

**Comment by tsloughter** [comment]
Nice, that is exactly what I'm looking for.

**Comment by tomas-abrahamsson** [comment]
I've merged and it is included in 3.28.1, which I pushed just now.
