### ISSUE TITLE
multiple output formats

### ISSUE THREAD

**Issue by tsloughter** [tomas-abrahamsson/gpb#121]
It doesn't appear to currently be an option but would it be possible, and accepted as a patch, to support both compiling to a file the generated source and returning the records like `to_proto_defs`?

**Comment by tomas-abrahamsson** [comment]
Yes, probably, but care may need to be taken to make sensible decisions about output formats. Eg: to file and to proto defs at the same time: both to files? or to file and the other as return value?

Would you care to elaborate a bit on your use case?

**Comment by tsloughter** [comment]
We have a rebar3 plugin that uses gpb to compile the protos to the erlang code but we also do some other stuff with the protos using the results from `to_proto_defs` -- like generating sql statements/tables for some of the proto definitions. So right now it has to do 2 runs to achieve this.

**Comment by tomas-abrahamsson** [comment]
An alternative vould be to first call `gpb:compile` with `to_proto_defs` and then call `gpb:proto_defs` with the defs returned from the first call. True it would be two calls to gpb, but only pass over the files, and not more passes over the structure. You would effectively be tapping the internal representation in the middle of the process.

**Comment by tsloughter** [comment]
Oh, right, I should have mentioned that, I couldn't find a way exposed to go from the representation to the files. If that is the case that I can call `gpb:proto_defs` that works for me, I'll give that a try later today.

**Comment by tomas-abrahamsson** [comment]
Yes, let's see if it works, it would be conceptually a little cleaner than multiple retur n formats, I think.

**Comment by tsloughter** [comment]
Thanks, this seemed to work. But surprisingly only saved like 1 second out of a run that takes in the 20s...

**Comment by tsloughter** [comment]
Also, the functions for making the module name aren't exported, in my case it isn't an issue since we aren't using any suffix or prefix right now, so simply `Mod = list_to_atom(ProtoName),` works, but there doesn't seem to be a way to get the module name that'll be needed in `gpb_compile:proto_defs/2` right now.

**Comment by tomas-abrahamsson** [comment]
You're right it makes sense to expose functionality for transforming proto file name to module name. I'll look into that. And it may also make sense to look into performance.
