### ISSUE TITLE
package confusion

### ISSUE THREAD

**Issue by tsloughter** [tomas-abrahamsson/gpb#123]
I'm curious why `use_packages` has an effect on whether protos can be imported from subdirectories. As in, why must `use_packages` be defined (and thus generated code for messages has the package name prepended) in order to do `import "google/protobuf/timestamp.proto";`.

Whether the package name is prepended and importing from a subdirectory of an included path seem like separate concerns?

It also seems that the google protobufs found in gpb's `priv/` are available when compiling (at least if `use_packages` is used) is this the case?

**Comment by tomas-abrahamsson** [comment]
Could you provide an example? The intention is that the import path is searched for each imported file, regardless of whether `use_packages` or not. But there is special handling for `syntax="proto3";`. If this is found, then the `priv/` dir is automatically added to the import path. Right now, I cannot find the reference, but I think that the set of _well-known_ proto files were included in Google protobuf 3.0.0, and that if syntax is proto3, then no extra include path option would be necessary to use them, at least with Google protobuf's `protoc`, so I tried to do mimic that in gpb.

Here's an example command line session of compiling two proto files, both times without the `-pkgs` (`use_pacakges`) option, but with different is the syntax. First with `syntax="proto3";`:

```
$ cat a.proto
syntax="proto3";
import "google/protobuf/timestamp.proto";
message M {
  Timestamp t0 = 10;
}

$ protoc-erl a.proto
$
```
Now with `syntax="proto2;"`
```
$ cat b.proto                            

import "google/protobuf/timestamp.proto";
message M {
  required Timestamp t1 = 11;
}

$ protoc-erl b.proto
Could not find import file "google/protobuf/timestamp.proto", tried:
  ./google/protobuf/timestamp.proto (no such file or directory (enoent))
$
```

**Comment by tsloughter** [comment]
Hm, interesting, I'll try making an example, maybe I was doing something else weird.

**Comment by tomas-abrahamsson** [comment]
There's one caveat (perhaps) with the way gpb works. It has nothing to do with `use_packages` per se, but might be useful to know about anyhow. It only happens with mixed proto2 and proto3 files: the auto-adding of `priv/` is not handled individually per proto3 file, but instead it is added when the first proto3 syntax file is seen. So the following scenario would be an unexpected success:
* top.proto imports sub1.proto and sub2.proto in this order
* sub1.proto is proto3
* sub2.proto is proto2, but imports google/protobuf/timestamp.proto
This accidentally succeeds, and changing the order of imports in top.proto will cause the compilation to fail.

I don't know how Google's protobuf `protoc` handles this scenario, hence the _perhaps_ in my first sentence.

**Comment by tsloughter** [comment]
Oh, I think I may have figured out what it was that had tripped me up before.

It was likely that I used types like:

```
google.protobuf.Timestamp start_time = 5;
```

that only work with `use_packages` and thinking those should work even if I don't want my messages prepended with the package name.

Not sure if that makes sense but I'm going to close this issue.
