### ISSUE TITLE
embedded message names

### ISSUE THREAD

**Issue by tsloughter** [tomas-abrahamsson/gpb#124]
I'm working on using the proto https://github.com/census-instrumentation/opencensus-proto/blob/master/opencensus/proto/trace/trace.proto in https://github.com/census-instrumentation/opencensus-erlang

I'd never used embedded messages with gpb before. I found that building with options `[strings_as_binaries, use_packages, mapfields_as_maps, msg_name_to_snake_case, {msg_name_prefix, "oc_"}, {module_name_suffix, "_pb"}]` the embedded messages end up with their parents name and a period:

So the record for the embedded message `Attributes` becomes `oc_span._attributes`.

Are there any configuration options for how embedded messages are handled? I didn't find any but wanted to be sure before I started looking at adding them.

**Comment by tomas-abrahamsson** [comment]
No, unfortunately, there aren't any such options. The full message name is subject for modification, be it snake_casing, lowercasing or whatever.

I've been restructuring name handling wrt #122. It is in progress, albeit a bit slowly. At the moment, it is work-in-progress, though. Would it be ok to await that first since it will probably step in the same pieces of code?

**Comment by tsloughter** [comment]
Ok, thanks. Yea, it can definitely wait. I can just use a modified version of the proto that copies the embedded messages out to the top level for the time being.

**Comment by tomas-abrahamsson** [comment]
On the `renaming-options` branch —see #122—I pushed a renaming opt, `dots_to_underscores`
`{rename,{msg_name,dots_to_underscores}}`. Does this do what you're aiming for?

**Comment by tsloughter** [comment]
The trailing underscore is fixed and dots to underscores works for embedded messages.

I'm going to go look in the code, are there any rename options so that a the record for an embedded message built with `use_packages` wouldn't be named:

```
opencensus_proto_trace_span_time_event_message_event
```

But instead just:

```
message_event
```

I might just use maps instead of records to not have to care about record names anymore, hehe, or always modify the `trace.proto` to get shorter names. But wanted to check first, I can understand if they need the full names to work properly.

**Comment by tomas-abrahamsson** [comment]
In the general case, packages/namespaces is of couse a way to resolve message name collisions. But I aree of course that the names tend to get far too long.

I couldn't come up with any good rename option for your usecase, so I think I'm proposing a `{rename,{msg_fqname,F}}` where F is a function that knows how to turn `'OpenCensus.Proto.Trace.Span.TimeEvent.MessageEvent'` into `message_event`, and that the function `F` look like `fun(ProtoBase::string(), Name::atom()) -> NewName::atom()` where `ProtoBase` would be the file's base name such as `"trace"` for `/.../trace.proto`.

If pressed for a rename option, then what would one go for? `{rename,{msg_fqname,drop_pkg}}`? Given that one can combine it with snake casing etc, it would take us to `span_time_event_message_event` which is not all the way you would want to go, so maybe `{rename,{msg_fqname,last_component}}` would be required.

However, going this road also makes the situation a bit brittle in that a perfectly reasonable addition to a some proto file could make compilation fail due names now colliding.  

(In any case, I should extend the renaming phase to check also for collisions after renames. It could theoretically happen already, but with either of the rename options above, the risk increases.)

Regardless of this, maps is generally a good way to go. Maps wins over records every time, in my opinion, and over lists of tuples (almost every time).

**Comment by tsloughter** [comment]
Maybe `base_msgname` for the rename function? Sort of like a basename for a file, the package and any parent messages are the full path to the message, and base name just gives the last name in the fullname?

But yea, definitely can get brittle. The reason I tend to not use maps is because they lack the compile time check for cases I know all fields that'll exist (not sure if dialyzer can do much for this on maps either...) and records have better access performance. In a perfect world Erlang would have ROK's frames proposal so there was no need to choose between the two :(

**Comment by tomas-abrahamsson** [comment]
I've pushed a pair of commits, one for checking for duplicates, and one that implements a `base_name` rename option. (I decided on `base_name` rather than `base_msgname` since it can be applied to other names as well, service names and package names)

**Comment by tsloughter** [comment]
Perfect! Exactly what I was looking for :) Thanks!

**Comment by tomas-abrahamsson** [comment]
Super! I'll merge it to master shortly. I will squash the fixup commit, so it will not be this branch exactly. And I will perhaps also fix a renaming for groups as well, I had forgotten about them.

**Comment by tomas-abrahamsson** [comment]
I just pushed 4.1.0, so I'm closing the issue.

**Comment by tsloughter** [comment]
Thanks!
