### ISSUE TITLE
Services can't have the same rpc

### ISSUE THREAD

**Issue by tsloughter** [tomas-abrahamsson/gpb#125]
Switching back to work and discovered the latest rename changes are an issue because it won't allow separate services to have the same rpc name.

I don't think these should result in duplication errors when the rpc methods are under separate services.

Simple example of what fails:

```
service Account {
  rpc Create (AccountCreateRequest) returns (AccountCreateResponse);
}

service Device {
  rpc Create (DeviceCreateRequest) returns (DeviceCreateResponse);
}
```

```
===> Running proto compiler...
===> Failed to compile protos/nucleus.proto:
Renaming to same name:
  Device/Create -> Create
  Account/Create -> Create
```

**Comment by tomas-abrahamsson** [comment]
Agree, I will fix.

**Comment by tomas-abrahamsson** [comment]
I just pushed 4.1.1, which contains a fix and an eunit test for this, so I'll be closing the issue.

**Comment by tsloughter** [comment]
Yup, thanks!
