### ISSUE TITLE
{invalid_version_format,[]} when running make

### ISSUE THREAD

**Issue by andrerfcsantos** [tomas-abrahamsson/gpb#127]
When i try to run make, i get the following error:

```
[andre@andre-pc gpb-master]$ make
Proto-compiling the description definition...
{"init terminating in do_boot",{{invalid_version_format,[]},[{gpb,assert_version_format,1,[{file,"src/gpb.erl"},{line,154}]},{gpb,version_as_string,0,[{file,"src/gpb.erl"},{line,120}]},{gpb_compile,format_erl,4,[{file,"src/gpb_compile.erl"},{line,1748}]},{gpb_compile,do_proto_defs_aux2,4,[{file,"src/gpb_compile.erl"},{line,694}]},{gpb_compile,do_proto_defs_aux1,3,[{file,"src/gpb_compile.erl"},{line,616}]},{gpb_compile,'-c/2-lc$^0/1-0-',2,[{file,"src/gpb_compile.erl"},{line,1094}]},{gpb_compile,c,2,[{file,"src/gpb_compile.erl"},{line,1094}]},{init,start_em,1,[]},{init,do_boot,3,[]}]}}
init terminating in do_boot ({{invalid_version_format,[]},[{gpb,assert_version_format,1,[{_},{_}]},{gpb,version_as_string,0,[{_},{_}]},{gpb_compile,format_erl,4,[{_},{_}]},{gpb_compile,do_proto_defs_a

Crash dump is being written to: erl_crash.dump...done
make: *** [Makefile:330: descr_src/gpb_descriptor.erl] Error 1
```

I'm using protobuffers 3.5.1 with erlang 20.2.
I tried to run make after downloading the git repository. I also tried several other versions of gpb, got the same error. Am i doing something wrong or is this possibly a bug?

I tried this on 2 machines, one running Manjaro and another one running Centos 7, got the same errors on both.

**Comment by andrerfcsantos** [comment]
Got it working by downloading with ```git clone``` instead of downloading the zip's on the "Releases" section. Seems that ```make``` will complain if not run from a directory that is not a repository directory. Is this behavior intended?

**Comment by tomas-abrahamsson** [comment]
Ok, good. In short, at the moment, I've no plan to support building from a zip. The current behaviour for building from a zip is a bit unfortune, and a result of some other priorities, see [here](https://github.com/tomas-abrahamsson/gpb/blob/4.1.1/README.md#version-numbering) and [here](https://github.com/tomas-abrahamsson/gpb/blob/4.1.1/src/gpb.erl#L123-L156) for a bit more info. If there was a way to achieve these properties also for zips, I'd of course be open to adaptations.

 I suppose most people use the hex package and thus don't have the problem, but you're right it'd be better if `make` (and `rebar`) could show the error better. I'll make a note of this.

The build process goes something like this: `build/mk_version_hrl` is used to transform `include/gpb_version.hrl.in` to `include/gpb_version.hrl`, and it tries to figure the version out by checking for git tags. So when downloaded as a zip, there's no git tag (or even a .git dir), hence the error. Then the version number is included gpb itself, and also in generated code.

Ok to close given the above?

**Comment by andrerfcsantos** [comment]
I completely missed that section of README, thanks for pointing it out.

In one of my attempts, `make` did complain explicitly about not finding a ```.git``` directory, but i was unable to reproduce that error since. It's still a confusing and weird error though, because of all the things you expect to go wrong with `make`, running it on a non-git directory is pretty low on the list.

My suggestion to make this not a problem would be to include the "manual" installation steps as a section of README and make it more clear there. It would help people like me who are new to erlang and know nothing about tools like ```rebar```.

Yeah, it's ok to close, thanks for the reply.

**Comment by tomas-abrahamsson** [comment]
Yes, completely agree running in a non-git repo is not exactly the most obvious of things. A section in the README is a good idea. Maybe even a helper script. I'll see what I can do.

**Comment by tomas-abrahamsson** [comment]
Hi again, I've revisited this issue, and implemented both a better error message when compiling outside of a git repository, such as a downloaded auto-generated tar or zip from github release page, and also make a script for extracting gpb from a git repository. I added [a section to the README](https://github.com/tomas-abrahamsson/gpb/blob/4.1.3/README.md#building-outside-of-a-git-work-tree) about it.

Here's a transcript when compiling github's auto-generated release file, ie from outside of a git-repo:
```
$ wget -O gpb-4.1.3.tar.gz https://github.com/tomas-abrahamsson/gpb/archive/4.1.3.tar.gz
$ tar xfpz gpb-4.1.3.tar.gz 
$ cd gpb-4.1.3/ 
$ make
Generating include/gpb_version.hrl...
Generating include/gpb_version.hrl...
ERROR: Building outside a git work tree is not supported,
       unless the source has first been exported.
       This is for the version number to get correct.
       To build outside a git work tree, first export it:
       Start with a git clone, then run helpers/export-from-git.
       For further info, see the README.md, the section section
       named Building outside of a git work tree

       Github automatically generates tar/zip files from tags,
       but these will unfortunately not do, since the version
       number does not get set correctly.
Makefile:399: recipe for target 'include/gpb_version.hrl' failed
make: *** [include/gpb_version.hrl] Error 1
$
```

And here' an abbreviated transcript from exporting from  a git repo and compiling the exported result. The version number gets pulled from the tags, and the tar file contains a `gpb_version.hrl` with a ready-baked version.
```
$ git clone git://github.com/tomas-abrahamsson/gpb.git
$ cd gpb
$ ./helpers/export-from-git 
Exporting version 4.1.3 -> gpb-4.1.3.tar.gz

$ tar xfpz .../gpb-4.1.3.tar.gz 
$ cd gpb-4.1.3 
$ make
mkdir -pv ebin
mkdir: created directory 'ebin'
erlc -Wall +debug_info -Iinclude -pa ebin -o ebin src/gpb.erl
erlc -Wall +debug_info -Iinclude -pa ebin -o ebin src/gpb_analyzer.erl
erlc -Wall +debug_info -Iinclude -pa ebin -o ebin src/gpb_codegen.erl
...
Generating ebin/gpb.app...
$
```
