### ISSUE TITLE
Use_packages options seems not working

### ISSUE THREAD

**Issue by gnolnuhc** [tomas-abrahamsson/gpb#129]
In the doc it mentioned there is an option for using package name as namespace. But I did not find any example. Searching the code I found 'use_packages'. So I tried adding {use_packages, true} into my gpb_opts. Generated code did compile successfully. But during run time when I try to call encode_msg, it causes such an error as `** exception error: no case clause matching `.

**Comment by gnolnuhc** [comment]
Sorry. It was caused by my compilation options. I had multiple beam files generated but with different gpb_opts.

**Comment by tomas-abrahamsson** [comment]
No problems, glad it sorted itself out
