### ISSUE TITLE
Improper interpretation of nested extend block

### ISSUE THREAD

**Issue by pguyot** [tomas-abrahamsson/gpb#135]
According to [language guide](https://developers.google.com/protocol-buffers/docs/proto#nested-extensions), extended blocks declared nested into message definitions should not belong to the nested message. It only impacts the scope. Yet, it is a common construct.

Typically:
```
message A {
}

message B {
    extend A {
        optional B b = 42;
    }
}
```

is (mostly) identical to:
```
message A {
}
message B {
}
extend A {
    optional B b = 42;
}
```
or
```
message B {
}

message A {
    optional B b = 42;
}
```

gbp currently considers field b is part of message B. With default options it will generate the following record definitions:
```
-ifndef('A_PB_H').
-define('A_PB_H', true).
-record('A',
        {
        }).
-endif.

-ifndef('B_PB_H').
-define('B_PB_H', true).
-record('B',
        {b                      :: #'B'{} | undefined % = 42
        }).
-endif.
```

**Comment by tomas-abrahamsson** [comment]
Hi, thanks for reporting, I will take a look at it.

**Comment by tomas-abrahamsson** [comment]
I've just pushed 4.1.7 which fixes this issue, so I'm closing. Please feel free to just re-open should there be anything more about it.
