### ISSUE TITLE
Custom encode/decode

### ISSUE THREAD

**Issue by tsloughter** [tomas-abrahamsson/gpb#137]
I think this would be like the translate feature gpb has for `Any` but work for any message.

My issue is wanting to have a `Uuid` message type that in the decoded map is not another map `#{uuid => <<....>>}` but instead just the binary `<<....>>`. And when encoding the uuid being able to take just the binary.

Would this be an appropriate feature for gpb or better to be done separately?

**Comment by tomas-abrahamsson** [comment]
To generalize translations to other type of (sub-)messages, not only `Any` is probably a relatively small effort, I think. I'll look into it.

To apply translations also to top-level messages, one would also have to change `encode_msg/1,2` to take an extra argument, the message name, at least when generating for records. For maps, it already takes this argument, but generally it would be needed for records as well. I suppose this is not a big limitation for you at the moment?

**Comment by tomas-abrahamsson** [comment]
Hi, I just pushed 4.2.0, which include a `{translate_type,{{msg,MsgName},Translations}}` option. It is a generalization of the previous `any_translate`, which now expands to the `translate_type`. Hence closing ticket, please feel free to just reopen if there is anything more.
