### ISSUE TITLE
Decode keys as binaries instead of as atoms

### ISSUE THREAD

**Issue by hachreak** [tomas-abrahamsson/gpb#138]
Hi at all,
Ill show you an example of what I mean:

```protobuf
message m {
  uint32 i1 = 1;
}
```

I'd like to decode something like:

```erlang
#{<<"i1">> => 17} 
```

Instead of

```erlang
#{i1 => 17} 
```

Do you think it's possible to add this feature as the "maps" option in rebar3.config?

**Comment by fenollp** [comment]
What kind of use case makes keys as binaries better than as atoms?
Is it that otherwise too many atoms are created? I'm just curious :)

**Comment by hachreak** [comment]
I'm working with mongodb and all the keys are treated as binary strings.
So, when you are reading you have a Map with binary strings instead of atoms.
Have to different way to see the same data could be a mess in some cases. XD
Just an example, in a test to check that a msg is written properly I have to manually translate atoms to keys before run the check.

**Comment by tomas-abrahamsson** [comment]
I see. Couldn't this easily be solved by:
```erlang
keys_to_binary(Map) ->
    maps:fold(
      fun(K, V, Acc) when is_map(V) ->
              Acc#{atom_to_binary(K) => keys_to_binary(V)};
         (K, V, Acc) ->
              Acc#{atom_to_binary(K) => V}
      end,
      #{},
      Map).

atom_to_binary(K) ->
    erlang:atom_to_binary(K, utf8).
```
Example:
```erlang
12> mapkeys:keys_to_binary(#{abc => #{def => 1}, ghi => 2}).
#{<<"abc">> => #{<<"def">> => 1},<<"ghi">> => 2}
```

**Comment by tomas-abrahamsson** [comment]
> Have to different way to see the same data could be a mess in some cases.
> Just an example, in a test to check that a msg is written properly I have to manually translate atoms to keys before run the check.

Sorry, forgot to comment about this: If you would add a function somewhere that passes the result from `decode_msg` into the `keys_to_binary` from previous post, you could convert keys to binaries automatically without having to do any manual translation, would that be ok?

**Comment by hachreak** [comment]
Hi @tomas-abrahamsson 
thanks for reply. 
I already implemented a function to apply to the `decode_msg` result to convert atom to binary.
But because the plugin compile in a erlang source code, I think it make sense (for performance I mean) to have a way to specify that I want binary instead of atoms in the generated `.erl` file. 
What do you think? It need too headache to implement it? :smile: 
I can try to make it if you drive me inside the code.. XD

**Comment by tomas-abrahamsson** [comment]
Yes, there are performance differences, but some are surprising. Measuring before making assumptions is always a good idea.
The first benchmark comparison is for small messages (throughput, higher values are better, the "pre/post conversion" means keys are atoms, and conversion to binary is with a `maps:fold` as outlined previously.)

operation | binary keys | pre/post conversion
------------ | -------------- | -------------------------
serialize to binary | 25.19 MB/s | 23.48 MB/s
deserialize from binary | 45.61 MB/s | 29.68 MB/s

Next for larger messages:

operation | binary keys | pre/post conversion
------------ | -------------- | -------------------------
serialize to binary | 21.29 MB/s | 30.16 MB/s
deserialize from binary | 35.03 MB/s | 38.38 MB/s

These are microbenchmarks, I ran `make maps-benchmarks` in the benchmarks subdirectory.

I can't explain precisely why for larger messages the pre/post conversion is faster. The benchmarks were run under the same conditions, an unloaded machine, not virtualized, same hw, same sw versions of everything etc. Serialization must compare map keys; when keys are atoms, it is only one machine word to compare, whereas for binaries, the vm must compare contents of binaries, which means more memory cells to compare. Differences in memory layout may also have impact.

In case you want to reproduce the benchmarks above or just experiment, then I've pushed a few branches: `binary-map-keys`, `tmp-benchmarks-bin-keys-pre-post-conversion` and `tmp-benchmarks-bin-keys-builtins`. I will remove those branches in a while, so don't count on them long term. The `binary-map-keys` branch does what you were after, except that it produces the wrong type definitions: with atoms for keys.

Another problem I found is that it is not possible to specify very any particularly accurate types at all with binary keys:
```erlang
% cat x.erl 
-module(x).
-type some_message() :: #{<<"key1">> => integer()}.
% erlc x.erl
x.erl:2: syntax error before: "key1"
```

**Comment by tomas-abrahamsson** [comment]
Hi again, despite performance measurements not always indicating improvements, I decided to include this anyway, mostly for reasons of inter-op with other libaries. So in the 4.3.0 which I pushed yesterday, there is a new option, `{maps_key_type, binary | atom}` for this. (Default is still `atom`). So I'll be closing this issue.

**Comment by hachreak** [comment]
Thanks a lot @tomas-abrahamsson for your work! :smile:

**Comment by tomas-abrahamsson** [comment]
You're welcome! Sorry it took so long.
