### ISSUE TITLE
with gpb option msg_name_to_lower, specifying a .proto package induces error

### ISSUE THREAD

**Issue by geib** [tomas-abrahamsson/gpb#139]
I am using rebar3_gpb_plugin 2.2.9, which pulls in pgb version 4.1.8.

When I specify the gpb option msg_name_to_lower for compiling .proto files, any .proto file with a 'pacakge  com.echostar.scci' line results in the error:

Error: {not_found_in_dict,'com.echostar.scci',[]}
[{gpb_names,dict_fetch,2,
            [{file,"/Users/geib/git/cse.scb2.sms_proto/_build/default/plugins/gpb/src/gpb_names.erl"},
             {line,381}]},
 {gpb_names,'-do_rename/2-fun-4-',3,
            [{file,"/Users/geib/git/cse.scb2.sms_proto/_build/default/plugins/gpb/src/gpb_names.erl"},
             {line,434}]},
 {lists,map,2,[{file,"lists.erl"},{line,1239}]},
 {lists,map,2,[{file,"lists.erl"},{line,1239}]},
 {gpb_names,rename_defs,2,
            [{file,"/Users/geib/git/cse.scb2.sms_proto/_build/default/plugins/gpb/src/gpb_names.erl"},
             {line,88}]},
 {gpb_compile,do_file_or_string,2,
              [{file,"/Users/geib/git/cse.scb2.sms_proto/_build/default/plugins/gpb/src/gpb_compile.erl"},
               {line,502}]},
 {rebar3_gpb_compiler,compile,3,
                      [{file,"/Users/geib/git/cse.scb2.sms_proto/_build/default/plugins/rebar3_gpb_plugin/src/rebar3_gpb_compiler.erl"},
                       {line,170}]},
 {rebar3_gpb_compiler,compile,4,
                      [{file,"/Users/geib/git/cse.scb2.sms_proto/_build/default/plugins/rebar3_gpb_plugin/src/rebar3_gpb_compiler.erl"},
                       {line,115}]}]

**Comment by tomas-abrahamsson** [comment]
Thanks for reporting! I've just pushed 4.1.9 which i believe fixes the bug, so I'm closing the issue. Please feel free to just re-open if you should discover anything is still missing!
