### ISSUE TITLE
Error reading protobuf containing bytes

### ISSUE THREAD

**Issue by jibreis** [tomas-abrahamsson/gpb#140]
hey,
i have a protobuf file as it follows:
```
(...)
message TorrentWrapper{
    string group = 1;
    bytes content = 2;
    string id = 3;
}

message ClientMessage {
    oneof msg {
        (...)
        TorrentWrapper torrentWrapper = 6;
    }  
```
Using a java client, i create a new protobuf `ClientMessage` containing a `TorrentWrapper` and send it  to my erlang server through a socket to decode it:

Client
```
ClientWrapper.TorrentWrapper torr = ClientWrapper.TorrentWrapper.newBuilder()
        .setGroup("group")
        .setId(uniqueId)
        .setContent(ByteString.copyFrom(Files.readAllBytes(file.toPath()))).build();

wrapper = ClientWrapper.ClientMessage.newBuilder()
        .setTorrentWrapper(torr).build();

socket.getOutputStream().write(wrapper.getSerializedSize());
wrapper.writeTo(socket.getOutputStream());
```

Server:
```
{tcp, Socket, Data} ->
     {_, {T, D}} =  client_wrapper:decode_msg(Data, 'ClientMessage'),
	case T of
		torrentWrapper ->
			(...)
```
The problem is, when i send a bigger bytes content - say, for example, 1mb - it crashes in the decoding. This doesn't happen when i send a small string "hey", though. [Here's a gist the error report.](https://gist.github.com/jibreis/0f950b7292a89929871c17ce72e54025)
Can somebody tell what i'm doing wrong or missing? Thanks!

Edit: After some investigation, i found out it crashes when the whole protobuf is equal or bigger than 128bytes

**Comment by tomas-abrahamsson** [comment]
On the Erlang side, how do you do framing? Dou you use a `{packet, N} ` option? I do not know what the `wrapper.getSerializedSize() ` does, but one possibility is that it returns a [wire encoded varint](https://developers.google.com/protocol-buffers/docs/encoding#varints). In these, if the high bit is set, it indicates it is not the last octet, and the lower 7 bits are part of the (little endian encoded) value. This could perhaps explain why it fails for lengths of 128 or more.

**Comment by jibreis** [comment]
i'm using {packet, 1}.
after some time using java to send protobufs to erlang, I've noticed that before sending the whole protobuf i initially need to send it's size - that's why i'm using `wrapper.getSerializedSize()` which returns an int.

**Comment by tomas-abrahamsson** [comment]
I see. I think `{packet, 4}` is what you are after then. A Java `int` is 32 bits (signed) if I remember correctly. Thus 4 octets.

**Comment by jibreis** [comment]
Yeah, that was pretty much the problem. For anyone having this problem or similar, don't forget you need to manually send the size of the probuff in a byte array:

```
byte[] size = ByteBuffer.allocate(4).putInt(wrapper.getSerializedSize()).array();
socket.getOutputStream().write(size);
```

The same thing applies to reading:
```
CodedInputStream in = CodedInputStream.newInstance(socket.getInputStream());
byte[] header = in.readRawBytes(4);
int size = ByteBuffer.wrap(header).getInt();
byte[] data = in.readRawBytes(size);
```

Thanks for the help and all the work put in this implementation for erlang :slightly_smiling_face:

**Comment by tomas-abrahamsson** [comment]
Glad it got sorted out, and thanks for returning with the solution!
