### ISSUE TITLE
With proto3, default enum value appears on the wire when set as an integer

### ISSUE THREAD

**Issue by jabarszcz** [tomas-abrahamsson/gpb#143]
In `proto3`, default values should not appear on the wire and this is handled correctly when the Erlang term to be encoded is an atom. When using the integer value 0, on the other hand, it does appear on the wire.

```bash
$cat > x.proto <<EOF
syntax='proto3';
enum an_enum {
    DEFAULT_VAL = 0;
}

message a_message {
    an_enum field = 1;
}
EOF
$ ./gpb/bin/protoc-erl -v always -I. x.proto
$ erlc -I ./gpb/include/ x.erl
$ erl
Erlang/OTP 19 [erts-8.3.5.1] [source] [64-bit] [smp:4:4] [async-threads:10] [hipe] [kernel-poll:false]

Eshell V8.3.5.1  (abort with ^G)
1> rr("x.hrl").
[a_message]
2> x:encode_msg(#a_message{field='DEFAULT_VAL'}).
<<>>
3> x:encode_msg(#a_message{field=0}).
<<8,0>>
```

**Comment by jabarszcz** [comment]
The enums are thus special in that they have 2 default values that can be passed in for encoding: 0 and the atom associated with the first value. A possible fix could be to handle multiple type defaults [here](https://github.com/tomas-abrahamsson/gpb/blob/master/src/gpb_gen_encoders.erl#L340-L353) and [here](https://github.com/tomas-abrahamsson/gpb/blob/master/src/gpb.erl#L1278-L1280) an then to choose what to do for decoding based on an option such as `decode_enums_as_atoms` or something like that.

**Comment by tomas-abrahamsson** [comment]
Thanks for a clear and detailed report. I'll look into it. On decoding the approach of gpb is to decode to an atom if possible, and to an integer otherwise (it could have been encoded with a newer .proto where more enum values were defined). I think this is still the reasonable way to do, and no `decode_enums_as_atoms` would be needed. But on encoding, there is clearly a bug.

**Comment by tomas-abrahamsson** [comment]
I just pushed a fix to the `proto3-enum-encode` branch (a temporary branch). Could you try it out?

**Comment by jabarszcz** [comment]
Just tried it out, and it works well! Also, you are right for decoding, the current approach is perfectly fine. Thanks for the quick response :100:

**Comment by tomas-abrahamsson** [comment]
Super! I'll include it in an upcoming release.

**Comment by tomas-abrahamsson** [comment]
I just pushed 4.2.1, which includes this fix.
