### ISSUE TITLE
gpb infected with GPL?

### ISSUE THREAD

**Issue by KrzysiekJ** [tomas-abrahamsson/gpb#152]
In commit 6b2ca4eb66f46de410d5f7639186c3e66066e49a, PropEr was added as a dependency. As PropEr is GPL-licensed, does it mean that gpb is now GPL-licensed too?

Refs proper-testing/proper#29.

**Comment by tomas-abrahamsson** [comment]
I see. gpb under GPL was never my intention, my mistake. Having read up on the referenced issue, I think, very unfortunately, that the prop_gpb will have to be reverted, at least until an excemption clause is explicitly added to PropEr's license.

**Comment by fenollp** [comment]
Wait no PropEr does not get shipped along gpb on an installation, it is only a test dependency. There is no way this can alter gpb's license, right? So people should be able to keep using GPB like nothing changed.

People working on GPB dev/internals, explicitly bringing GPB's test dependencies in, these are the one that PropEr's license impacts, right?

I really don't want to see a PBT test suite disabled once again due to EQC/licensing issues...

**Comment by fenollp** [comment]
See https://github.com/proper-testing/proper/issues/4#issuecomment-343896

**Comment by KrzysiekJ** [comment]
Regarding the linked comment, the license of libstdc++ contains [an exemption](https://gcc.gnu.org/onlinedocs/libstdc++/manual/license.html):

> When you use GCC to compile a program, GCC may combine portions of
> certain GCC header files and runtime libraries with the compiled
> program. The purpose of this Exception is to allow compilation of
> non-GPL (including proprietary) programs to use, in this way, the
> header files and runtime libraries covered by this Exception.

There is no such exemption in PropEr. I acknowledge the fact that PropEr maintainers may have no intention to pursuit anyone in this regard, but PropEr has many contributors, so this becomes problematic (I guess that otherwise a license exemption would already be added).

If PropEr is chosen to be reverted, then another issue may be whether mere `git revert` is sufficient for this purpose or is rewriting of history needed.

**Comment by fenollp** [comment]
> the header files and runtime libraries

The difference here and my point being: gpb has no **runtime dependency** on PropEr, only an (optional, even) test/dev time dependency.

**Comment by tomas-abrahamsson** [comment]
I'm thinking a way forward could be to change the license of `prop_gpb.erl` (only) to GPL 3 (and put a note about that in the top-level COPYING.LIB. Of course all contributors to the original `gpb_eqc.erl` would have to be contacted and accept. If not all can be reached, or someone objects, the `prop_gpb.erl` should be taken out.

As to whether reverted or some other way: I certainly hope a git revert would be enough, I mean projects can change license. Is there anything prior written about it?

**Comment by tomas-abrahamsson** [comment]
4.3.3 is now out, with the merge reverted, so I'll be closing this ticket.

(I find it to be very unfortunate, but I also think this was the only way for the prop_gpb.erl in its current form)
