### ISSUE TITLE
error compile .proto in macos mojave

### ISSUE THREAD

**Issue by kentkwan** [tomas-abrahamsson/gpb#157]
execute command 
`../gpb/bin/protoc-erl -I. x.proto` 
escript: exception error: no match of right hand side value {error,bad_directory}
  in function  erl_eval:expr/5 (erl_eval.erl, line 453)
  in call from erl_eval:local_func/6 (erl_eval.erl, line 567)
  in call from escript:eval_exprs/5 (escript.erl, line 872)
  in call from erl_eval:local_func/6 (erl_eval.erl, line 567)
  in call from escript:interpret/4 (escript.erl, line 788)
  in call from escript:start/1 (escript.erl, line 277)
  in call from init:start_em/1
```
.
├── gpb
│   └── bin
── test
    └── x.proto
```

**Comment by tomas-abrahamsson** [comment]
Do you have an `ebin` directory next to the `bin` directory that contains `protoc-erl`? The `protoc-erl` begins by setting up paths to that `ebin` dir and continues execution by calling into the `gpb_compile` module.

**Comment by kentkwan** [comment]
the gpb directory contains what i checkout the gpb project by git

**Comment by tomas-abrahamsson** [comment]
Have you compiled gpb? Either `cd gpb; make` or `cd gpb; rebar3 compile`. I'll fix it so that the error message gets better when using `protoc-erl` from a freshly cloned repo.

**Comment by kentkwan** [comment]
It works, thank you.
