### ISSUE TITLE
Generating descriptor fails complaining about multiple packages

### ISSUE THREAD

**Issue by tsloughter** [tomas-abrahamsson/gpb#162]
Adding reflection to grpcbox I hit a snag when testing. I have a project for interop testing with other implementations of grpc. It has 3 protos, https://github.com/tsloughter/grpcbox/tree/master/interop/proto and each is in the package `grpc.testing`.

When building the protos it fails when compiling `test.proto` with the following error/stacktrace:

```
===> Uncaught error: {case_clause,
                                ['grpc.testing','grpc.testing',
                                 'grpc.testing']}
===> Stack trace to the error location:
[{gpb_compile_descr,defs_to_package,1,
                    [{file,"descr_src/gpb_compile_descr.erl"},{line,65}]},
```

Is the fact that it imports the two other protos and those define the package they are each in resulting in this crash? That shouldn't be the case, right?

**Comment by tsloughter** [comment]
And related to reflection, would you be open to modules including a function that returns the name of the proto the module was built from?

There is a reflection request that takes the file name and return the descriptor.

**Comment by tomas-abrahamsson** [comment]
I'll take a look at the crash shortly. A function the proto the module was built from sounds like a good idea. I suppose it ought to return the basename of the proto, with extension?

**Comment by tomas-abrahamsson** [comment]
I just pushed 4.6.0, which should fix the crash, and also generate a `source_basename/0` function. 

About any extra lookup functions, would you want to keep this ticket open, and we can discuss details, or we close the ticket, and if you find anything that needs extra support, we'll just take it from there?

**Comment by tsloughter** [comment]
Nice, thanks it builds now.

I'll close this and open another ticket in a few minutes. I'm not sure if there is any new functions needed but I need to kick around some ideas.
