### ISSUE TITLE
record_info wrapper for all the Messages

### ISSUE THREAD

**Issue by AnufrievDE** [tomas-abrahamsson/gpb#172]
Hello, it could be considered a small enhancement request, maybe not fresh and not important enough, and maybe even meaningless. 

But, why not to include record_info wrapper for all the records generated from .proto files?
What do you think?

Just something like that:
generated_module_pb:_record_info(fields, msgName1) -> record_info(fields, msgName1);
generated_module_pb:_record_info(fields, msgName2) -> record_info(fields, msgName2);
...
generated_module_pb:_record_info(fields, msgNameN) -> record_info(fields, msgNameN);

generated_module_pb:_record_info(size, msgName1) -> record_info(size, msgName1);
...
generated_module_pb:_record_info(size, msgNameN) -> record_info(size, msgNameN).

I just forced to add such a wrappers somewhere in code to simplify/combine some part of equal handling for different Messages. This is why I was thinking why not to add such a _record_info wrapper in generated gpb files?

**Comment by tomas-abrahamsson** [comment]
Have you seen the generated introspection functions `get_msg_defs/0`, `find_msg_def/1` and `fetch_msg_def/1`? Here's a small example module to show how they can be used to achieve what I think you want, given the `'Person'` message from the [README](https://github.com/tomas-abrahamsson/gpb/blob/master/README.md)
```erlang
-module(x_record_info).
-export([fields/1, size/1]).
-include_lib("gpb/include/gpb.hrl").
fields(MsgName) ->
    [Nm || #?gpb_field{name=Nm} <- x:fetch_msg_def(MsgName)].

size(MsgName) ->
    length(fields(MsgName)).
```
Some example of how it can be used:
```erlang
1> x_record_info:fields('Person').
x_record_info:fields('Person').
[name,id,email]
2> x_record_info:size('Person').
x_record_info:size('Person').
3
```

If you do not want the dependency to the `gpb.hrl` for the `#?gpb_field{}` record, you can use the [`defs_as_proplists` option](https://hexdocs.pm/gpb/gpb_compile.html#option-defs_as_proplists) or the [`defs_as_maps` option](https://hexdocs.pm/gpb/gpb_compile.html#option-defs_as_maps)

Does this solve your needs?

**Comment by AnufrievDE** [comment]
Thank you for the answer and usefull links. Yes, most probably my needs will be more than solved by exprecs functionality. But to be honest, I didn't get the idea how to use "-compile([Str])" to insert exprecs functions working with records into generated code. Probably I need first to try to deal with exprecs.

Or it could be even better for me to use maps intead of records with help of option msgs_as_maps.
