### ISSUE TITLE
maps_unset_optional functionality for proto2, proto3 messages

### ISSUE THREAD

**Issue by AnufrievDE** [tomas-abrahamsson/gpb#175]
Hello @tomas-abrahamsson,

I just would like you to have a look at the behavior I see by manipulating maps_unset_optional option with proto2 and proto3 messages. Could you check are all the test results below expected or not?

According to the documentation of maps_unset_optional, I assume that type_default values for fields should not be set at decoding of empty msg ```<<>>``` when using proto3 syntax, is not it? Or this option has a bit another meaning for proto3 messages against proto2 messages?
```
For messages as maps, for optional fields, if not set, the maps_unset_optional option specifies the Erlang-internal representation; **both how it is expected to be found at encoding, and how decoding will return it**:
omitted
This means it is not included in the map. This is the default. (since gpb version 4.0.0)
present_undefined
This means it is present and has the value undefined. This was the default before gpb version 4.0.0.
```

1) {maps_unset_optional,omitted} with other opts below.
Options:
```
{gpb_opts, [{i, "protos"}, 
            {module_name_suffix, "_pb"},
            {o, "src"},           
            strings_as_binaries,
            maps,
            msgs_as_maps,
            {maps_unset_optional,omitted},
            {maps_key_type, binary},
            json,
            json_always_print_primitive_fields,
            {json_format, jiffy},
            type_specs,
            use_packages]}.
```
Test:
```
1> DecodedEmptyProto3Msg = configuration_pb:decode_msg(<<>>,craft_module).
#{<<"lang_code">> => <<>>,<<"lang_name">> => <<>>,
  <<"module_code">> => <<>>,<<"module_desc">> => <<>>,
  <<"module_id">> => 0,<<"module_name">> => <<>>,
  <<"version_code">> => <<>>,<<"version_id">> => 0,
  <<"version_name">> => <<>>}
2>
2> VerifyDecodedEmptyProto3Msg = configuration_pb:verify_msg(DecodedEmptyProto3Msg,craft_module).
ok
3>
3> EncodeDecodedEmptyProto3Msg = configuration_pb:encode_msg(DecodedEmptyProto3Msg,craft_module).
<<>>
4>
4>
4> EncodedEmptyProto3MapMsg = configuration_pb:encode_msg(#{},craft_module).
<<>>
5>
5> VerifyEmptyProto3MapMsg = configuration_pb:verify_msg(#{},craft_module).
ok
6>
6>
6>
6>
6> DecodedEmptyProto2Msg = configuration_internal_pb:decode_msg(<<>>,cs_module).
#{<<"module_desc">> => '$undef',<<"module_id">> => '$undef',
  <<"version_id">> => '$undef'}
7>
7> VerifyDecodedEmptyProto2Msg = configuration_internal_pb:verify_msg(DecodedEmptyProto2Msg,cs_module).
** exception error: {gpb_type_error,{{bad_integer,uint32,unsigned,32},
                                     [{value,'$undef'},{path,'cs_module.module_id'}]}}
     in function  configuration_internal_pb:mk_type_error/3 (/mnt/d/craft_conf_server/src/configuration_internal_pb.erl, line 12494)
     in call from configuration_internal_pb:v_msg_cs_module/3 (/mnt/d/craft_conf_server/src/configuration_internal_pb.erl, line 11294)
8>
8> EncodeDecodedEmptyProto2Msg = configuration_internal_pb:encode_msg(DecodedEmptyProto2Msg,cs_module).
** exception error: an error occurred when evaluating an arithmetic expression
     in operator  band/2
        called as '$undef' band 127
     in call from configuration_internal_pb:e_varint/2 (/mnt/d/craft_conf_server/src/configuration_internal_pb.erl, line 1907)
     in call from configuration_internal_pb:encode_msg_cs_module/3 (/mnt/d/craft_conf_server/src/configuration_internal_pb.erl, line 384)
9>
9>
9> EncodedEmptyProto2MapMsg = configuration_internal_pb:encode_msg(#{},cs_module).
** exception error: no function clause matching configuration_internal_pb:encode_msg_cs_module(#{},<<>>,undefined) (/mnt/d/craft_conf_server/src/configuration_internal_pb.erl, line 378)
10>
10> VerifyEmptyProto2MapMsg = configuration_internal_pb:verify_msg(#{},cs_module).
** exception error: {gpb_type_error,{{missing_fields,[module_id,version_id,
                                                      module_desc],
                                                     cs_module},
                                     [{value,#{}},{path,cs_module}]}}
     in function  configuration_internal_pb:mk_type_error/3 (/mnt/d/craft_conf_server/src/configuration_internal_pb.erl, line 12494)
```

2) {maps_unset_optional,present_undefined} with other opts below.
Options:
```
{gpb_opts, [{i, "protos"}, 
            {module_name_suffix, "_pb"},
            {o, "src"},        
            strings_as_binaries,
            maps,
            msgs_as_maps,
            {maps_unset_optional,present_undefined},
            {maps_key_type, binary},
            json,
            json_always_print_primitive_fields,
            {json_format, jiffy},
            type_specs,
            use_packages]}.
```
Test:
```
1> DecodedEmptyProto3Msg = configuration_pb:decode_msg(<<>>,craft_module).
#{<<"lang_code">> => <<>>,<<"lang_name">> => <<>>,
  <<"module_code">> => <<>>,<<"module_desc">> => <<>>,
  <<"module_id">> => 0,<<"module_name">> => <<>>,
  <<"version_code">> => <<>>,<<"version_id">> => 0,
  <<"version_name">> => <<>>}
2>
2> VerifyDecodedEmptyProto3Msg = configuration_pb:verify_msg(DecodedEmptyProto3Msg,craft_module).
ok
3>
3> EncodeDecodedEmptyProto3Msg = configuration_pb:encode_msg(DecodedEmptyProto3Msg,craft_module).
<<>>
4>
4>
4> EncodedEmptyProto3MapMsg = configuration_pb:encode_msg(#{},craft_module).
** exception error: no function clause matching configuration_pb:encode_msg_craft_module(#{},<<>>,undefined) (/mnt/d/craft_conf_server/src/configuration_pb.erl, line 514)
5>
5> VerifyEmptyProto3MapMsg = configuration_pb:verify_msg(#{},craft_module).
** exception error: {gpb_type_error,{{missing_fields,[module_id,module_code,
                                                      module_name,module_desc,version_id,version_code,
                                                      version_name,lang_code,lang_name],
                                                     craft_module},
                                     [{value,#{}},{path,craft_module}]}}
     in function  configuration_pb:mk_type_error/3 (/mnt/d/craft_conf_server/src/configuration_pb.erl, line 8544)
6>
6>
6>
6>
6> DecodedEmptyProto2Msg = configuration_internal_pb:decode_msg(<<>>,cs_module).
#{<<"module_code">> => undefined,
  <<"module_desc">> => undefined,<<"module_id">> => undefined,
  <<"module_name">> => undefined,
  <<"version_id">> => undefined,
  <<"version_ref">> => undefined}
7>
7> VerifyDecodedEmptyProto2Msg = configuration_internal_pb:verify_msg(DecodedEmptyProto2Msg,cs_module).
** exception error: {gpb_type_error,{{bad_integer,uint32,unsigned,32},
                                     [{value,undefined},{path,'cs_module.module_id'}]}}
     in function  configuration_internal_pb:mk_type_error/3 (/mnt/d/craft_conf_server/src/configuration_internal_pb.erl, line 11571)
     in call from configuration_internal_pb:v_msg_cs_module/3 (/mnt/d/craft_conf_server/src/configuration_internal_pb.erl, line 10663)
8>
8> EncodeDecodedEmptyProto2Msg = configuration_internal_pb:encode_msg(DecodedEmptyProto2Msg,cs_module).
** exception error: an error occurred when evaluating an arithmetic expression
     in operator  band/2
        called as undefined band 127
     in call from configuration_internal_pb:e_varint/2 (/mnt/d/craft_conf_server/src/configuration_internal_pb.erl, line 1847)
     in call from configuration_internal_pb:encode_msg_cs_module/3 (/mnt/d/craft_conf_server/src/configuration_internal_pb.erl, line 385)
9>
9>
9> EncodedEmptyProto2MapMsg = configuration_internal_pb:encode_msg(#{},cs_module).
** exception error: no function clause matching configuration_internal_pb:encode_msg_cs_module(#{},<<>>,undefined) (/mnt/d/craft_conf_server/src/configuration_internal_pb.erl, line 378)
10>
10> VerifyEmptyProto2MapMsg = configuration_internal_pb:verify_msg(#{},cs_module).
** exception error: {gpb_type_error,{{missing_fields,[module_id,version_id,
                                                      version_ref,module_code,module_name,module_desc],
                                                     cs_module},
                                     [{value,#{}},{path,cs_module}]}}
     in function  configuration_internal_pb:mk_type_error/3 (/mnt/d/craft_conf_server/src/configuration_internal_pb.erl, line 11571)
```

I am interesed in it due to the following question (partly discussed here https://github.com/tomas-abrahamsson/gpb/issues/82) -
What should I do to guarantee that proto3(hopefully) message recieved or packed by me has all the fields set? 

Firstly for test needs, to make sure messages were packed by me correctly, secondly for checking that received and decoded messages were packed correctly by the client, to decide as fast as possible whether service ready to handle such a request or not.

For the moment, according to the test results above I see 3 ways:
1) To use proto2 with ```required``` words (with potential further problems when changing APIs probably);

2) To use proto3 with options ```{maps_unset_optional, present_undefined}```. And let decode_msg/encode_msg crash, or write a function that checks that there are no undefined fields maybe...;

3) To use your proposal from main page with has_<field> boolean fields (but I don't see it is the best option to be honest) -
```
For proto3 syntax
For proto3, there is neither required nor optional nor default=<x> for fields. Instead all fields are implicitly optional, and if missing in the binary to decode, they always decode to the type-specific default value. Also, it is not possible to determine whether a value was present---with a type-specific value---or not; no has_<field>() methods are generated (at least for scalars). If you need detection of "missing" data, you must define has_<field> boolean fields and set them appropriately.

This maps directly and naturally to Erlang.
```

Thanks in advance!

**Comment by tomas-abrahamsson** [comment]
At first sight the `'$undef'` and `badarith` crash looks odd for the proto2 examples you show, but I suspect you have some `required` fields? If this guess is right, these errors are essentially due to the empty binary `<<>>` not being a valid (proto2) representation of the message. Fields are missing. (Is this guess right? Or would it be possible to share the proto?)

> What should I do to guarantee that proto3(hopefully) message recieved or packed by me has all the fields set?

I'm not sure I follow entirely. Let's take packing first, and let's say you trust gpb to encode valid results given the proto. Then I take your question to be that you have some additional requirements that some values must be set, that this clashes with proto3's view of all fields being optional, and that you want some way to verify that the fields are set. Is this what you meant?

One way is of course to go proto2 and have `required`. Another way is for you to wrap your calls to gpb with some additional code of your own, that performs additional validations. You have additional requirements on what fields must be set, after all.

Let's move to decoding. I suppose you trust your client to have the same proto definitions (or compatible at least) so that the binary to decode is valid for the proto definition you have, but you additionally want to verify that the client has set some fields, is this correctly understood?

With proto3, this is not generally possible. Note that with proto3, on decoding, there is no difference between the client setting an `uint32` field to 0 (its type-default) or omitting it. On decoding as well as over the wire, there is no difference.

I agree about the proposal with `has_⟨field⟩` is not very attractive, but it is actually what's proposed in the protobuf documentation, although I cannot find any reference to it at the moment.

Widening the perspective a bit:

An additional way to go could be to use wrappers, ie instead of an `uint32` field (for example), you have `google.protobuf.UInt32Value`. The `google.protobuf.UInt32Value` is a message with one field, `value`, and messages (as opposed to scalars) can be omitted or present, so at least it is possible to see if a value was present or not after decoding. I suppose it is about as attractive as the `has_⟨field⟩` approach, and I guess you would still want to write extra validation code.

With gpb, there is also the possibility to use translations: to inject an extra layer of code called before encode, after decode and instead of verify. You can hook it in per field and also on a message level. An obvious drawback is that whenever your proto changes, your translations need to change too, so keeping many translations up to date and coherent seems to be a big job.

Not trying to argue on somebody else's behalf, but it seems to me a not insignificant part in why everything is optional in proto3, is to tackle the forwards/backwards compatibility issue, when you have old data, but your proto defintions have evolved, or vice versa. And the general recommendations to handle it appears to be to write some more code to take care of some different cases.

Sorry for many non-answers...

**Comment by AnufrievDE** [comment]
First of all, thank you for the fast support, it is great!

> (Is this guess right? Or would it be possible to share the proto?)

Yes this guess is right, here is proto2 message:
```
message cs_module {
    required uint32       module_id = 1;
    required uint32       version_id = 2;
    optional cs_version   version_ref = 3;
    optional string       module_code = 4;
    optional string       module_name = 5;
    required string       module_desc = 6;
}
```

> Then I take your question to be that you have some additional requirements that some values must be set, that this clashes with proto3's view of all fields being optional, and that you want some way to verify that the fields are set. Is this what you meant?

Yes, that's what I meant. I am new in protobuf, and it seem to be a main problem :)
I am trying to manipulate options you provide to achieve something that probably forbidden by protobuf itself.
> One way is of course to go proto2 and have required. Another way is for you to wrap your calls to gpb with some additional code of your own, that performs additional validations. You have additional requirements on what fields must be set, after all.

Yep, seems so.

> Let's move to decoding. I suppose you trust your client to have the same proto definitions (or compatible at least) so that the binary to decode is valid for the proto definition you have, but you additionally want to verify that the client has set some fields, is this correctly understood?
With proto3, this is not generally possible. Note that with proto3, on decoding, there is no difference between the client setting an uint32 field to 0 (its type-default) or omitting it. On decoding as well as over the wire, there is no difference.

Sounds clear. I.e. if I use proto3 syntax I should accept all of the not set fields will be set with type-default values at decoding/encoding. But, then it seems that it should be forbidden to use ```maps_unset_optional``` with proto3 messages?(option probably should be ignored) Because, currentl,y it does not match the option description(now I got that it is correct for optional fields for proto2 messages only), that states that the encoding/decoding behavior will be similar:
```both how it is expected to be found at encoding, and how decoding will return it```
Moreover it does not works well. Returning to the test results and ```maps_unset_optional``` option, if I set it as ```present_undefined```, I can see that encoding and verifying of proto3 message fails if message does not has at least one of the the fields set(although all of them should be optional in proto3):
configuration_pb.erl
```
v_msg_craft_module(#{<<"module_id">> := F1,
		     <<"module_code">> := F2, <<"module_name">> := F3,
		     <<"module_desc">> := F4, <<"version_id">> := F5,
		     <<"version_code">> := F6, <<"version_name">> := F7,
		     <<"lang_code">> := F8, <<"lang_name">> := F9},
		   Path, TrUserData) ->
   ...;
v_msg_craft_module(M, Path, _TrUserData)
    when is_map(M) ->
    mk_type_error({missing_fields,
		   [module_id, module_code, module_name, module_desc,
		    version_id, version_code, version_name, lang_code,
		    lang_name]
		     -- maps:keys(M),
		   craft_module},
		  M, Path);
v_msg_craft_module(X, Path, _TrUserData) ->
    mk_type_error({expected_msg, craft_module}, X, Path).
```

> With gpb, there is also the possibility to use translations: to inject an extra layer of code called before encode, after decode and instead of verify. You can hook it in per field and also on a message level. An obvious drawback is that whenever your proto changes, your translations need to change too, so keeping many translations up to date and coherent seems to be a big job.

Thanks, will try to look at the translations or to follow a general recommendation to satisfy requirements I want, by adding an additional handling.

**Comment by tomas-abrahamsson** [comment]
> But, then it seems that it should be forbidden to use maps_unset_optional with proto3 messages?

True, there's no difference for scalar fields, but for sub-messages, there's a difference (so should be neither forbidden nor ignored):
```
$ cat x3.proto
syntax='proto3';
message Top {Sub s = 1;}
message Sub {uint32 i = 1;}
$ # compile with maps, {maps_key_type,binary}, {maps_unset_optional,omitted}, ...
$ erl
1> x3_pb:decode_msg(<<>>, 'Top').
#{}
2> x3_pb:decode_msg(x3_pb:encode_msg(#{<<"s">> => #{}}, 'Top'), 'Top').
#{<<"s">> => #{<<"i">> => 0}}
```
True also that the description for the `maps_unset_optional` should mention how it works in relation to proto3. And also that the section of the README on proto3 should be a bit more verbose. I'll see to it.

(Will fix handling of `{maps_key_type,binary}` for the `missing_fields` error, too)

> Moreover it does not works well. Returning to the test results and `maps_unset_optional` option, if I set it as present_undefined, I can see that encoding and verifying of proto3 message fails if message does not has at least one of the the fields set(although all of them should be optional in proto3):

I do not follow. With proto3, the fields are indeed optional, but with the option `maps_unset_optional` set to `present_undefined`, you have to set the map fields, but you have to set them to `undefined` to indicate that they do not have a value. This is like it is for records. The history is that when maps were about to enter the scene in Erlang 17, I didn't have much experience with maps yet, so I thought it would be very simple to support. Basically same mechanisms as for records, just no record name in the syntax. So the first approach to map support in gpb had `undefined` for indicating an optional value was not set, just like with records. Only later on, I realized that this is not the way one want it to work, normally, and I added the option `{maps_unset_optional,omitted}` and later made it the default. These days, I think the `{maps_unset_optional,present_undefined}` was mostly a mistake. I've kept it mostly for the case someone happens to use it from early map days, and still rely on it, but I have thought of eventually deprecating and removing it.

**Comment by tomas-abrahamsson** [comment]
> True also that the description for the maps_unset_optional should mention how it works in relation to proto3. And also that the section of the README on proto3 should be a bit more verbose. I'll see to it.

Here are some proposals for new wording for the [README section on proto3](https://github.com/tomas-abrahamsson/gpb/blob/improve-doc-on-optionality-for-proto3/README.md#For-proto3-syntax) and for the [`maps_unset_optional` option documentation](https://github.com/tomas-abrahamsson/gpb/blob/improve-doc-on-optionality-for-proto3/src/gpb_compile.erl#L390-L412). I hope this makes things a bit more clear.

(The branch, and thus the links above, is temporary and will be removed eventually after having been merged,)

**Comment by AnufrievDE** [comment]
Thanks for update

**Comment by tomas-abrahamsson** [comment]
> Are you planning to fix some code in scope of this issue?

Yes, only the change below for `map_key_type=binary`. I just pushed 4.10.6 with this fix.

```erlang
    mk_type_error({missing_fields,
		   [module_id, module_code, ...] -- maps:keys(M),
		   craft_module},
		  M, Path);

    mk_type_error({missing_fields,
		   [<<"module_id">>, <<"module_code">>, ...] -- maps:keys(M),
		   craft_module},
		  M, Path);
```
