### ISSUE TITLE
The generated file is too large

### ISSUE THREAD

**Issue by Fang-Li** [tomas-abrahamsson/gpb#180]
Excuse me, how to map different source files to the generated files after compilation, 
instead of compiling into a file that imports all other files

**Comment by tomas-abrahamsson** [comment]
You would want one erlang module per proto file? It is not something gpb can do. What is your use-case, wht do you want that?

**Comment by Fang-Li** [comment]
Yes. I want a erlang module corresponding to a proto file, otherwise due to the continuous increase of the interface, the resulting file is already very large, which is not convenient for git management.
 I see, thank you. 
My use case is used as a gateway for a microservice cluster, the name of the microservice and the request parameters of the interface are encapsulated together.

**Comment by tomas-abrahamsson** [comment]
Can you version-control only the .proto file and not the generated code?

**Comment by Fang-Li** [comment]
Yes, currently using gpb as an invisible tool.
Therefore, the generated files are managed by git, not the protocol files.
Thank you for your answer.
