### ISSUE TITLE
submessages as oneof decode with default values even with `maps_unset_optional omitted`

### ISSUE THREAD

**Issue by fbernier** [tomas-abrahamsson/gpb#181]
Hi,

First, sorry for the lack of failing test or proper info on this issue. I'll improve it in case you confirm the behavior is not normal.

I have the following

```
syntax = "proto3";
message MessageA {
    message MessageB { int32 field1 = 1; }
    oneof maybe_message_b { MessageB message_b = 1; }
    int32 field_2 = 2;
}
```

and the following gpc options:

```
{gpb_opts, [
  {i, "priv/schemata"},
  include_as_lib,
  {nif, true},
  {o_nif_cc, "c_src"},
  {strings_as_binaries, true},
  {maps, true},
  {maps_oneof, flat},
  {maps_unset_optional, omitted}, 
  {type_specs, true}
]}.
```

When encoding and not setting any value to message_b, I would expect it not to show up in the decoded message, but it's there as

```
{message_b, [field1, 0]}
```

Is this the expected behavior?

**Comment by tomas-abrahamsson** [comment]
Hi, could you explain a bit more, for example where is the `{message_b, [field1, 0]}` printout from? It does not look like something from gpb. This is what I get when I compile your proto with your options:
```erlang
%% "Not setting any value to message_b", is this how you mean, for example an empty map?
1> x:encode_msg(#{}, 'MessageA').    
<<>>
2> x:decode_msg(<<>>, 'MessageA').   
#{field_2 => 0}
```

**Comment by fbernier** [comment]
Hey,

Sorry I slimmed down the real issue thinking it would reproduce the problem but apparently it didn't. Could you please give me the few commands you use to be able to quickly test things up in the shell like you did? Compiling the schema and passing the options. It would speed thing up for me in order to provide a repro.

Thanks

**Comment by tomas-abrahamsson** [comment]
No problems, stuff something like below into a shell script or Makefile or similar. It assumes the file is `x.proto`.
```shell
export PATH_TO_GPB=/path/to/somewhere/gpb
protoc --cpp_out=`pwd` x.proto
$PATH_TO_GPB/bin/protoc-erl -o `pwd` -nif -strbin \
    -maps -maps_oneof flat -maps_unset_optional omitted -type x.proto
erlc -Wall +debug_info -I$PATH_TO_GPB/include x.erl
g++ -g -fPIC -Wall -O3 -I/usr/include -c x.nif.cc
g++ -fPIC -O3 -I/usr/include -c x.pb.cc
g++ -g -fPIC -shared -O3 -Wall -I/usr/include -o x.nif.so \
    x.nif.o x.pb.o \
  -L/usr/lib/x86_64-linux-gnu -lprotobuf \
  -Wl,-rpath=/usr/lib/x86_64-linux-gnu
```
Then just start `erl` in this directory and you should be good to go.

**Comment by fbernier** [comment]
So I've been unable to reproduce for now, and I'm currently suspecting the encoder I am using (not gpb) to be the one causing the issue. I'll close this for now and reopen if it ends up being needed.

**Comment by tomas-abrahamsson** [comment]
Ok.
