### ISSUE TITLE
Compile and install

### ISSUE THREAD

**Issue by Scott-Zou-Developer** [tomas-abrahamsson/gpb#183]
When I compile it with commond "make" .
This is my first time to compile.

root@ubuntu:/usr/developEnviroment/gpb-master# make
Generating include/gpb_version.hrl...
ERROR: Building outside a git work tree is not supported,
       unless the source has first been exported.
       This is for the version number to get correct.
       To build outside a git work tree, first export it:
       Start with a git clone, then run helpers/export-from-git.
       For further info, see the README.md, the section section
       named Building outside of a git work tree

       Github automatically generates tar/zip files from tags,
       but these will unfortunately not do, since the version
       number does not get set correctly.
make: *** [Makefile:429: include/gpb_version.hrl] Error 1

How to compile and install this project?

**Comment by tomas-abrahamsson** [comment]
Could you describe your setup, did you clone the gpb repo, or did you download a zip or tar file from github or something similar?

If you downloaded a zip or tar, then this use case is not supported (because the build will try to fetch the version from the git tags) and you need to export the code from a git clone first by running `helpers/export-from-git` as the text says.

If you are in a git repo, could you paste the output from the command `git rev-parse --is-inside-work-tree`?

**Comment by Scott-Zou-Developer** [comment]
Step 1: download zip form github
wget https://codeload.github.com/tomas-abrahamsson/gpb/zip/master

Step 2: unzip master

Step 3: make
root@ubuntu:/usr/developEnviroment/gpb-master# make
Generating include/gpb_version.hrl...
ERROR: Building outside a git work tree is not supported,
unless the source has first been exported.
This is for the version number to get correct.
To build outside a git work tree, first export it:
Start with a git clone, then run helpers/export-from-git.
For further info, see the README.md, the section section
named Building outside of a git work tree

   Github automatically generates tar/zip files from tags,
   but these will unfortunately not do, since the version
   number does not get set correctly.
make: *** [Makefile:429: include/gpb_version.hrl] Error 1

root@ubuntu:/usr/developEnviroment/gpb-master# helpers/export-from-git
fatal: Not a git repository (or any of the parent directories): .git
Cannot chdir to , the toplevel of the working tree

**Comment by tomas-abrahamsson** [comment]
The gpb build process requires a git work tree, with tags, to get the version numbering right. Github's automatically created zip files do not work. Please try doing a git clone and building from that instead.

**Comment by Scott-Zou-Developer** [comment]
Step 1: git clone https://github.com/tomas-abrahamsson/gpb
Step 2: cd gpb
Step 3: git checkout -b 3.20.2 3.20.2
Step 4: make

successful.

Thank you very much!

**Comment by tomas-abrahamsson** [comment]
You're welcome!

**Comment by tomas-abrahamsson** [comment]
I'll be closing this. Feel free to reopen or open another one if there is anything more!

**Comment by nisbus** [comment]
Hi, I'm hitting this issue as well from a cloned submodule copied inside a docker container.  
The issue might be specific to gitlab but I thought I'd at least document it in case someone else hits this.
Feel free to close it if you don't think it's relevant to the project (I'll update it if I find a solution).  
  
I'm using gitlab for this and gpb is a submodule of my project.  
  
```
project
    /modules
        /gpb
```

* Gitlab runner clones submodules  
* Dockerfile uses COPY ./modules /modules
* Dockerfile calls RUN cd /modules/gpb && make all

output:
```
Submodule 'modules/gpb' (https://github.com/tomas-abrahamsson/gpb.git) registered for path 'modules/gpb'
Cloning into '/project/modules/gpb'...
Submodule path 'modules/gpb': checked out '84cd72d9918f3729b45cacd9471c415720b263e1'

Step 6/47 : COPY ./modules /modules
 ---> 99d1d368f29c
Step 7/47 : RUN cd /modules/gpb && make all
 ---> Running in 08497e5c23c0
Generating include/gpb_version.hrl...
ERROR: Building outside a git work tree is not supported,
           unless the source has first been exported.
           This is for the version number to get correct.
           To build outside a git work tree, first export it:
           Start with a git clone, then run helpers/export-from-git.
           For further info, see the README.md, the section section
           named Building outside of a git work tree
           Github automatically generates tar/zip files from tags,
           but these will unfortunately not do, since the version
           number does not get set correctly.
make: *** [Makefile:430: include/gpb_version.hrl] Error 1
```
  
I've tried to create the worktree in the runner before running make but the result is the same.
  
```
  before_script:
    - git submodule update --init --recursive
    - cd $CI_PROJECT_DIR/modules/gpb && git checkout master
    - cd $CI_PROJECT_DIR/modules/gpb && git worktree add --track -b build  origin/master
```  
  
running docker build locally works fine with the same setup.

**Comment by nisbus** [comment]
Just changed the Dockerfile to delete the submodule and clone inside the build, that works :man_shrugging:

**Comment by tomas-abrahamsson** [comment]
Could the reason have been that `.git` is in some [.dockerignore file](https://docs.docker.com/engine/reference/builder/#dockerignore-file)? and then maybe inside the docker the it is not a git repo anymore? And hence the error message.

I'm no expert on docker and COPY, but found this [SO question](https://stackoverflow.com/questions/42132475/hidden-file-env-not-copied-using-docker-copy) about another hidden file, ".env" not making it into the docker container.

If this is the case, then it would explain why cloning inside the docker makes a difference. 

Side note, in case it would be of use: Starting from 4.16.1, there is also a pre-exported-from-git gpb-x.y.z.tar.gz on [the releases page](https://github.com/tomas-abrahamsson/gpb/releases). It is generated by a github workflow, so should be there always in releases from now on. Granted, one has to know the version number to figure out the download-link, so just getting "the latest" is trickier. There are some google hits for how to automate it if needed.
