### ISSUE TITLE
The URL in  readme is not exist

### ISSUE THREAD

**Issue by aqian1103** [tomas-abrahamsson/gpb#187]
hi， the follow url in readme is not exist and cannot reach: 
https://www.rebar3.org/docs/using-available-plugins#section-protocol-buffers

**Comment by tomas-abrahamsson** [comment]
The new url is https://rebar3.org/docs/configuration/plugins/#protocol-buffers after the rebar3 site restructuring. Thanks for noticing, I will update, but it will be a few days due to other things in queue.

**Comment by aqian1103** [comment]
> The new url is https://rebar3.org/docs/configuration/plugins/#protocol-buffers after the rebar3 site restructuring. Thanks for noticing, I will update, but it will be a few days due to other things in queue.

Thanks for your reply.

**Comment by tomas-abrahamsson** [comment]
I fixed the link in the 4.15.0 which I just pushed, so I'll be closing this issue.
