### ISSUE TITLE
Publish with rebar3

### ISSUE THREAD

**Issue by tsloughter** [tomas-abrahamsson/gpb#191]
Looks like gpb gets published with `rebar` set as the build tool: https://hex.pm/packages/gpb

I never noticed since rebar3 doesn't care but mix does and it tries to use `rebar2` to build it and seeing people on slack having issues with it.

I'd suggest publishing with rebar3 so it properly sets the build tool to use.

**Comment by tomas-abrahamsson** [comment]
Thanks for notifying! I'll look into it. (I've been using `mix hex.publish` from a helper script that auto-generates a temporary `.exs` file, that indeed sets the `build_tools` to [`["rebar", "make"]`](https://github.com/tomas-abrahamsson/gpb/blob/4.15.1/helpers/package-for-hex.pm#L105). This dates back from rebar2-times surely. I suppose either setting it to `"rebar3"` or else use `rebar3` itself to publish, will do the trick.)

**Comment by tsloughter** [comment]
Yea, if that script is working for you then I'd just replace `rebar` with `rebar3` and republish, no need to publish with rebar3 itself at this point

**Comment by tomas-abrahamsson** [comment]
I just pushed 4.16.0, and the build tool now says `rebar3` instead of `rebar`.
