### ISSUE TITLE
JSON encoding when a field is not a 'primitive'

### ISSUE THREAD

**Issue by shashank2000** [tomas-abrahamsson/gpb#193]
Hi there!

Thanks very much for gpb, I've been trying to get the `to_json` function to work with Protobuf messages of the type

      message First {
        string version = 1;
        oneof attr {
          Second second = 2;
          Third third = 3;
        }
     }

Essentially, pb messages within pb messages. Do the json encodings not support this?
What I'd like ideally is
{"version" : "X", "third": {whatever-third-is}};

Is there a flag that allows this that I am missing? I've used
        {json_key_format, string},
          {json_format, eep18},
          {json_always_print_primitive_fields, true},
          {json_preserve_proto_field_names, true}

**Comment by tomas-abrahamsson** [comment]
Messages in messages (in oneof) should work. You might want to specify also the `json` option. What error do you get? Here is my attempt:
```erlang
35> code:add_patha("/path/to/gpb/ebin").
true
36> Options = [{json_key_format, string}, {json_format, eep18}, {json_always_print_primitive_fields, true}, {json_preserve_proto_field_names, true}].
[{json_key_format,string},
 {json_format,eep18},
 {json_always_print_primitive_fields,true},
 {json_preserve_proto_field_names,true}]
37> gpb_compile:file("x.proto", [json] ++ Options).
ok
38> c(x, [{i, "/path/to/gpb/include"}]).
{ok,x}
39> rr(x).
['First','Second','Third',field,gpb_oneof,rpc]
40> x:to_json(#'First'{version = "1.0", attr = {third, #'Third'{g1 = 1}}}).
[{"version",<<"1.0">>},{"third",[{"g1",1}]}]
```
where `x.proto` is based on your file:
```proto
syntax = 'proto3';
message First {
    string version = 1;
    oneof attr {
      Second second = 2;
      Third third = 3;
    }
}

message Second {
     uint32 f1 = 1;
}

message Third {
     uint32 g1 = 1;
}
```

**Comment by shashank2000** [comment]
Hey @tomas-abrahamsson thanks for the reply! I get a case_clause error, on closer inspection it seems like this is happening because my .proto messages are all given a common prefix once they are turned into erlang records courtesy the msg_name_prefix option, but the `to_json_msg_prefix_first()` function that is generated by gpb doesn't seem to honor that. When it is going through the cases in this function (to encode to JSON) it seems like the cases are all erlang records without the prefix. Let me know if any of this makes sense.

**Comment by tomas-abrahamsson** [comment]
Seems you got it working. Here's a transcript from my own session with msg_name_prefix:
```erlang
55> RenameOptions = [{msg_name_prefix,"mmm_"}].
[{msg_name_prefix,"mmm_"}]
56> gpb_compile:file("x.proto", [json] ++ Options ++ RenameOptions).
ok
57> c(x, [{i,"/path/to/gpb/include"}]).
{ok,x}
58> rr(x).
[field,gpb_oneof,mmm_First,mmm_Second,mmm_Third,rpc]
59> x:to_json(#'mmm_First'{version = "1.0", attr = {third, #'mmm_Third'{g1 = 1}}}).
[{"version",<<"1.0">>},{"third",[{"g1",1}]}]

```
