### ISSUE TITLE
Consider support for #Inf, #-Inf and NaN (OTP 24+)

### ISSUE THREAD

**Issue by paulo-ferraz-oliveira** [tomas-abrahamsson/gpb#199]
In case https://github.com/erlang/otp/pull/4537 gets merged, there might be a potential change to consider to `gpb`.

(this is not an issue, per se)

**Comment by tomas-abrahamsson** [comment]
Ah, interesting, thanks for the heads-up!

**Comment by paulo-ferraz-oliveira** [comment]
@tomas-abrahamsson, should we close this? This was just a heads-up, since I knew not otherwise. Unless you wanna keep it for a while longer. (?)

**Comment by tomas-abrahamsson** [comment]
Yes  maybe better to close it for now. We can always reopen when that pr gets merged.
