### ISSUE TITLE
why "string" type spec is iodata

### ISSUE THREAD

**Issue by sairre** [tomas-abrahamsson/gpb#200]
Hi, why "string" type spec is "iodata()"? when i use chinese characters, such as  "我们”, it is a list of integer [25105,20204]  out of range of "iodata()".

**Comment by tomas-abrahamsson** [comment]
Hi, you're right, it looks like it should be `unicode:chardata()`. I will fix this in the next release.

**Comment by tomas-abrahamsson** [comment]
Hi, in 4.16.2, which was just released, it is now `unicode:chardata()` so I will close this.
