### ISSUE TITLE
gpb 4.16.2 does not compile

### ISSUE THREAD

**Issue by shturm-hippopo** [tomas-abrahamsson/gpb#201]
Trying to use latest gpb (4.16.2) - it does not compile.
4.16.1 had no issues on the same protobuf files and Erlang version.

Generating include/gpb_version.hrl...
mkdir -pv ebin
mkdir: created directory 'ebin'
erlc -Wall +debug_info -Iinclude -pa ebin -o ebin src/gpb.erl
erlc -Wall +debug_info -Iinclude -pa ebin -o ebin src/gpb_analyzer.erl
erlc -Wall +debug_info -Iinclude -pa ebin -o ebin src/gpb_codegen.erl
erlc -Wall +debug_info -Iinclude -pa ebin -o ebin src/gpb_codemorpher.erl
erlc -Wall +debug_info -Iinclude -pa ebin -o ebin src/gpb_compile.erl
erlc -Wall +debug_info -Iinclude -pa ebin -o ebin src/gpb_decoders_lib.erl
erlc -Wall +debug_info -Iinclude -pa ebin -o ebin src/gpb_defs.erl
erlc -Wall +debug_info -Iinclude -pa ebin -o ebin src/gpb_gen_decoders.erl
erlc -Wall +debug_info -Iinclude -pa ebin -o ebin src/gpb_gen_encoders.erl
erlc -Wall +debug_info -Iinclude -pa ebin -o ebin src/gpb_gen_introspect.erl
erlc -Wall +debug_info -Iinclude -pa ebin -o ebin src/gpb_gen_json_decoders.erl
erlc -Wall +debug_info -Iinclude -pa ebin -o ebin src/gpb_gen_json_encoders.erl
erlc -Wall +debug_info -Iinclude -pa ebin -o ebin src/gpb_gen_mergers.erl
erlc -Wall +debug_info -Iinclude -pa ebin -o ebin src/gpb_gen_nif.erl
erlc -Wall +debug_info -Iinclude -pa ebin -o ebin src/gpb_gen_translators.erl
erlc -Wall +debug_info -Iinclude -pa ebin -o ebin src/gpb_gen_types.erl
erlc -Wall +debug_info -Iinclude -pa ebin -o ebin src/gpb_gen_verifiers.erl
erlc -Wall +debug_info -Iinclude -pa ebin -o ebin src/gpb_lib.erl
erlc -Wall +debug_info -Iinclude -pa ebin -o ebin src/gpb_names.erl
erlc -Wall +debug_info -Iinclude -pa ebin -o ebin src/gpb_parse.erl
erlc -o src src/gpb_parse_old.yrl
erlc -Wall +debug_info -Iinclude -pa ebin -o ebin src/gpb_parse_old.erl
erlc -Wall +debug_info -Iinclude -pa ebin -o ebin src/gpb_scan.erl
erlc -o src src/gpb_scan_old.xrl
build/prepend_edoc_autogenerated "src/gpb_scan_old.erl" "src/gpb_scan_old.xrl"
erlc -Wall +debug_info -Iinclude -pa ebin -o ebin src/gpb_scan_old.erl
Proto-compiling the description definition...
erlc -Wall +debug_info -Iinclude -Iinclude -pa ebin -o ebin descr_src/gpb_compile_descr.erl
erlc -Wall +debug_info -Iinclude -Iinclude -pa ebin -o ebin descr_src/gpb_descriptor.erl
descr_src/gpb_descriptor.erl:125: unknown dialyzer warning option: no_underspecs
descr_src/gpb_descriptor.erl:129: unknown dialyzer warning option: no_underspecs
descr_src/gpb_descriptor.erl:134: unknown dialyzer warning option: no_underspecs
make[1]: *** [Makefile:287: ebin/gpb_descriptor.beam] Error 1

**Comment by tomas-abrahamsson** [comment]
What version of Erlang are you using? Are you by chance using Erlang from the master branch but before 24.0-rc1? The `-dialyzer({no_underspecs, fn/arity})` directive got added in erlang/otp#4517, which got merged a few days ago. If so, can you uplift to 24.0-rc1?

If you are on Erlang 23 or earlier, then something is fishy, gpb should only emit those directives if the major version is 24.

**Comment by shturm-hippopo** [comment]
Thank you for the reply. It appears we are using pre-rc1 R24. We will try to upgrade, and I will check again soon.
