### ISSUE TITLE
gpb 4.17.5 can't find version 

### ISSUE THREAD

**Issue by paulo-ferraz-oliveira** [tomas-abrahamsson/gpb#207]
Where once `.app.src` had `{vsn,"x.y.z"}`, it now has `{vsn,"./build/find-vsn --show-vsn"}`.

In a project that bumped from 4.17.3 to 4.17.5 this means it stopped working 😢: "ERROR: To build outside a git work tree, you must explicitly...".

Using `rebar3` I'm not sure where that work tree would be found... also, as per the README, I did create a `gpb.vsn` file, but don't know where to place it 🤣 

Thoughts?

**Comment by tomas-abrahamsson** [comment]
Try the 4.17.6 instead. (I had reworked version handling and got it wrong in 4.17.4 and 4.17.5.)

**Comment by paulo-ferraz-oliveira** [comment]
Hm... I think 4.17.6 has the same behaviour, but checking...

**Comment by paulo-ferraz-oliveira** [comment]
Nope, it's gone there. You can always remove 4.17.5 from Hex.pm :) 4.17.4 isn't there, for example.

Actually, without removing it, there's a way to mark versions as unusable: `rebar3 help hex retire`.

This seems to need no further handling, thanks @tomas-abrahamsson. I'll reopen if required.

**Comment by tomas-abrahamsson** [comment]
Yes, good point, had forgotten about that  I'll do it when I'm at a computer next. (I never uploaded 4.17.4 at all, that's why it isn't on hex.pm)

**Comment by tomas-abrahamsson** [comment]
Just out of curiosity, what did you do to get the 4.17.5 and not the latest version?

**Comment by paulo-ferraz-oliveira** [comment]
I bumped, patch by patch, 4.17.x starting from x = 0 😄 (which is why I knew .4 was not published)
