### ISSUE TITLE
mk_version_hrl error on windows

### ISSUE THREAD

**Issue by DominicGame** [tomas-abrahamsson/gpb#208]
using rebar3_gpb_plugin on windows
'.'  is not recognized as an internal or external command

gpb/build/mk_version_hrl:74

will 'gpb' support it on windows?

**Comment by tomas-abrahamsson** [comment]
It is the intention, but I do not have a windows to test it on. Would you be able to try out the (temporary) branch `windows-support-2`? I have attempted to rewrite the build helper in a way such that it hopefully works on windows too.

I suppose the change that broke it was the 9275efc7d6 commit in which the below had changed.
```
-    InGit = os:cmd("git rev-parse --is-inside-work-tree  2>&1"),
+    case os:cmd("./build/find-vsn --have-vsn") of
```

**Comment by DominicGame** [comment]
> 
> 
> It is the intention, but I do not have a windows to test it on. Would you be able to try out the (temporary) branch `windows-support-2`? I have attempted to rewrite the build helper in a way such that it hopefully works on windows too.
> 
> I suppose the change that broke it was the [9275efc](https://github.com/tomas-abrahamsson/gpb/commit/9275efc7d639bd404c1d0412cd926ec8d76ae98b) commit in which the below had changed.
> 
> ```
> -    InGit = os:cmd("git rev-parse --is-inside-work-tree  2>&1"),
> +    case os:cmd("./build/find-vsn --have-vsn") of
> ```

thanks for your reply!
I use 4.17.3 now.

I try 'window-support-2' like: 
{plugins, [{ rebar3_gpb_plugin, "2.20.1" }]}.

{overrides, [{override, rebar3_gpb_plugin, [{deps, [{gpb, ".*", {git, "https://github.com/tomas-abrahamsson/gpb.git", {tag, "window-support-2"}}}]}]}]}.

and I got:
ERROR Failed to find the <gpb>/build/find-vsn program.
  in path "build;C:\\Program Files\\erl-23.0\\erts-11.0\\bin;......(PATH content)"

I found add 'escript ' can fix it:
os:cmd("escript ./build/find-vsn --have-vsn")

but I got 'false', I check the code in find-vsn:
"514c1d6\n" = os:cmd("git describe --always --tags --match '[0-9]*.[0-9]*'") ====line:124
```
looks_like_vsn_output([C1 | _]=Str) when ?is_digit(C1) ->
    %% Examples of valid outputs:
    %%   "4.17.3"
    %%   "4.17.3-1-g0bfce0e"
    is_vsn_str_1(Str);
looks_like_vsn_output(_) ->
    false.
```
emmm. I have no idea about this

**Comment by tomas-abrahamsson** [comment]
> I found add 'escript ' can fix it:
os:cmd("escript ./build/find-vsn --have-vsn")

Good find! I adapted the code to this (force-pushed)

> but I got 'false', I check the code in find-vsn:
"514c1d6\n" = os:cmd("git describe --always --tags --match '[0-9].[0-9]'") ====line:124

This could happen if your git repo clone does not have any tags, or if it is a shallow clone. Could either of this be the case? (I'm not sure if detached head could cause such issues, will have to check)
Otherwise something else is the problem, maybe only on window. Do you get the expected output when running that git describe command in a command window manually? (For example if there could be some shell quote problem?)

**Comment by DominicGame** [comment]
> This could happen if your git repo clone does not have any tags, or if it is a shallow clone. Could either of this be the case? (I'm not sure if detached head could cause such issues, will have to check)
> Otherwise something else is the problem, maybe only on windows. Do you get the expected output when running that git describe command in a command window manually? (For example if there could be some shell quote problem?)

basic, I got these output
```
PS D:\tmp\gpb_win_support\_build\default\plugins\gpb> git describe
fatal: No annotated tags can describe 'd00b7fa728f3d95d45acbad0674c221909c0a2c0'.
However, there were unannotated tags: try --tags.
PS D:\tmp\gpb_win_support\_build\default\plugins\gpb> git describe --tags
4.17.6-1-gd00b7fa
PS D:\tmp\gpb_win_support\_build\default\plugins\gpb> git describe --always --tags --match '[0-9].[0-9]'
3.9-1080-gd00b7fa
PS D:\tmp\gpb_win_support\_build\default\plugins\gpb> erl
Eshell V11.0  (abort with ^G)
1> os:cmd("git describe --always --tags --match '[0-9].[0-9]'") .
"d00b7fa\n"
2> os:cmd("git describe --always --tags") .
"4.17.6-1-gd00b7fa\n"
3> os:cmd("git describe --tags") .
"4.17.6-1-gd00b7fa\n"
PS D:\tmp\gpb_win_support\_build\default\plugins\gpb> git --version
git version 2.31.1.windows.1
```

I take a look at 'D:\tmp\gpb_win_support\_build\default\plugins\gpb\.git\refs\tags'
there are many tag from 2.0 ->4.17.6 and t1 -> t5

finally, I try out:
```
git describe  --tags --always --match [0-9]*
4.17.6-1-gd00b7fa
git describe  --tags --always --match '[0-9].[0-9][0-9].[0-9]'
4.17.6-1-gd00b7fa
```
and
```
6> os:cmd("git describe --tags --match '[.0-9]*'").
"fatal: No names found, cannot describe anything.\n"
7> os:cmd("git describe --tags --match [0-9]*").
"4.17.6-1-gd00b7fa\n"
```
if it has single quotes in erl cmd, it won't work well, but it's ok in cmd
maybe we need a new pattern to replace '[0-9].[0-9]'

hope it can help you

**Comment by tomas-abrahamsson** [comment]
Thanks for trying out different commands. Based on this, could you try the following (note the asterisks):
```
1> os:cmd("git describe --always --tags --match [0-9]*.[0-9]*").
```

**Comment by DominicGame** [comment]
I try these commands
```
1> os:cmd("git describe --always --tags --match [0-9]*.[0-9]*").
"4.17.6-1-gd00b7fa\n"
2> os:cmd("git describe --always --tags --match [0-9]*").
"4.17.6-1-gd00b7fa\n"
```
I check some doc:
match pattern work as glob(7)
```
A '*' (not between brackets) matches any string, including the
       empty string.
.......
Note that wildcard patterns are not regular expressions, although
       they are a bit similar.  First of all, they match filenames,
       rather than text, and secondly, the conventions are not the same:
       for example, in a regular expression '*' means zero or more
       copies of the preceding thing.
```
and --debug git
```
git describe --always --tags --match [0-9]*.[0-9]* --debug
describe HEAD
No exact match on refs or tags, searching to describe
 lightweight        1 4.17.6
 lightweight        4 4.17.5
 lightweight        6 4.17.4
 lightweight       14 4.17.3
 lightweight       16 4.17.2
 lightweight       18 4.17.1
 lightweight       24 4.17.0
 lightweight       37 4.16.2
 lightweight       54 4.16.1
 lightweight       59 4.16.0
traversed 78 commits
more than 10 tags found; listed 10 most recent
gave up search at c214a1a82f8f32a5b92376d1aea4fd3107017554
4.17.6-1-gd00b7fa
```

1, I think [0-9]* and [0-9]*.[0-9]* is same pattern
2, git will search form newest tag
so
if you only need to match a tag start with a number and won't release a tag like '123abc', '[0-9]*' maybe enough

**Comment by tomas-abrahamsson** [comment]
My guess what was happenig is that on windwos, also the single-quotes got passed to `git describe`. On linux/unix on the other hand, the quotes are needed to stop the shell from expanding in case there would be any file that matches the version pattern, unlikely as it may be, but not impossible. The unix shell does not pass the single-quotes on (to the `git describe`).

On the branch, currently, it checks `os:type()` and runs the `git` command without single-quote on windows. Does building work for you with this?

I'm thinking on windows, with the WSL, there's probably be a shell and the quotes may be needed, but I don't know what `os:type()` would return in this context. The check currently tries to match `{win32,_}`.

> 1, I think [0-9]* and [0-9]\*.[0-9]\* is same pattern

Yes, I agree that in terms of version numbers and tags in practical use, they would be very similar. But I see no need to change it either, since I think the issue was with the quotes instead. (I think some of your asterisks got lost in the markdown rendering, which first got me a bit confused :) )

**Comment by DominicGame** [comment]
> On the branch, currently, it checks `os:type()` and runs the `git` command without single-quote on windows. Does building work for you with this?
> 
"gpb\src\gpb.app.src" need a 'escript' too
and it work well 👍 

> Side-track: I'm thinking on windows, with the WSL, there's probably be a shell and the quotes may be needed, but I don't know what `os:type()` would return in this context. The check currently tries to match `{win32,_}`. End of side-track.
> 
I use wsl+ubuntu try out:
```
Erlang/OTP 22 [erts-10.6.4] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1]

Eshell V10.6.4  (abort with ^G)
1> os:type().
{unix,linux}
```
I think that I should work with wsl instead of cmd/ps and we have solved this problem 🎉🎉🎉

**Comment by tomas-abrahamsson** [comment]
> gpb\src\gpb.app.src" need a 'escript' too
and it work well 👍

Ah, sorry, yes of corse!

```
|  1> os:type().
|  {unix,linux}
```
Ah, Good, then the `{win32,_}` match will work.

> I think that I should work with wsl instead of cmd/ps and we have solved this problem 🎉🎉🎉

Yes, haha :) Maybe that's the better option :)

I pushed the use of gpb.app.src fix, in case you would want to try it out. I plan to make a release and include that branch soon.

**Comment by tomas-abrahamsson** [comment]
Hi, I've just included this (including the gpb.app.src) in 4.17.7, so I'll be closing this issue. Would you discover there is still something that needs fixing, just re-open or open another issue. Many thanks for the help with trouble shooting and trying things out!
