### ISSUE TITLE
Add preprocessor check around no_underspec?

### ISSUE THREAD

**Issue by tsloughter** [tomas-abrahamsson/gpb#212]
I commit the code generated from protos to the repo in a project and that means if I generate the code on OTP 24 it won't build on earlier OTPs because it adds `-dialyzer({no_underspecs, encode_msg/2}).` to the module.

Can that be wrapped in a `-if(?OTP_RELEASE >= 24).` so it can still build on earlier OTPs?

**Comment by tomas-abrahamsson** [comment]
Yes, sounds ok, I'll do it. (Sorry for delayed answer)

**Comment by tomas-abrahamsson** [comment]
The 4.19.2 now contains such a preprocessor check, so I'll be closing this ticket.

**Comment by tsloughter** [comment]
Thanks! No worries at all on the "delay" :), awesome work
