### ISSUE TITLE
Outdated example 

### ISSUE THREAD

**Issue by Xevib** [tomas-abrahamsson/gpb#215]
I'm an erlang newbie and perhaps I'm wrong but i think the example [here](https://github.com/tomas-abrahamsson/gpb/blob/master/README.md?plain=1#L36) it's outdated due the example artity is 1 and the arity of the export [here](https://github.com/tomas-abrahamsson/gpb/blob/master/src/gpb.erl#L52) is 2

**Comment by tomas-abrahamsson** [comment]
In the generated module, `x` (first example) I believe the arity 1 is generated ehen generating for records as opposed to maps, but I'm not at the computer now so can't check. You are right that in the `gpb` module, the arity 2 exists. The `gpb` module is a data driven encoder and decoder so it is slower than the generated code.

**Comment by Xevib** [comment]
@tomas-abrahamsson it's true, i missed the step `protoc-erl` so it was a little meaningless. Now it works
Thank you for the quick answer

**Comment by tomas-abrahamsson** [comment]
No problems, you're welcome!
