### ISSUE TITLE
-spec for enum generated code is incorrect

### ISSUE THREAD

**Issue by geib** [tomas-abrahamsson/gpb#221]
I have a .proto file with enum definitions, and when I generate the erlang code I find that the -spec definitions for fqbin_to_msg_name() and msg_name_to_fqbin() are swapped, see below snippet.

```erlang
-spec msg_name_to_fqbin(_) -> no_return().
fqbin_to_msg_name(E) -> error({gpb_error, {badmsg, E}}).


-spec fqbin_to_msg_name(_) -> no_return().
msg_name_to_fqbin(E) -> error({gpb_error, {badmsg, E}}).
```

**Comment by tomas-abrahamsson** [comment]
Indeed, I see. I think dialyzer is ok either way, but I will fix it. Thanks for notifying.

**Comment by geib** [comment]
You are correct, it was edoc complaining.

**Comment by tomas-abrahamsson** [comment]
I just pushed 4.19.6 which fixes this issue.
