### ISSUE TITLE
How can i call gpb from my rebar.config?

### ISSUE THREAD

**Issue by Zabrane** [tomas-abrahamsson/gpb#224]
Hi All,

I've a project with a google protocol buffers definition (Ubuntu 20.04 LTS):
```bash
$ ls -1 src 
src/myapp.app.src
src/myapp_app.erl
src/myapp_sup.erl
src/myapp.erl
src/myapp_protocol.proto <---- the google protocol buffer def
```

How should i configure my `rebar.config` to ask `rebar3` to generate the source files from this google protocol buffers definition?

`src/myapp_protocol.proto` should produce:

```bash
$ ls -1 src 
src/myapp.app.src
src/myapp_app.erl
src/myapp_sup.erl
src/myapp.erl
src/myapp_protocol.proto <---- the google protocol buffer def
src/myapp_protocol.erl <---- generated from the definition
src/myapp_protocol.hrl <---- generated from the definition

$ rebar3
rebar3 3.19.0 on Erlang/OTP 24 Erts 12.3.2.6
```

Help appreciated.
Many thanks.

**Comment by tomas-abrahamsson** [comment]
Take a look at https://github.com/lrascao/rebar3_gpb_plugin it will generate source from the .proto using gpb

**Comment by Zabrane** [comment]
I found the plugin [here](https://rebar3.org/docs/configuration/plugins/#protocol-buffers)
