### ISSUE TITLE
to_json encodes `uint64` as an integer instead of a string

### ISSUE THREAD

**Issue by tmp-reg** [tomas-abrahamsson/gpb#232]
Our data has at most 53 bits, for values of type `uint64`, how does the `to_json` method encode them as integers rather than strings?

**Comment by tomas-abrahamsson** [comment]
The [Json mapping section in the langage guide](https://developers.google.com/protocol-buffers/docs/proto3#json) says that uint64 is to be represented in JSON as a string: "JSON value will be a decimal string." The Google protobuf library encodes them to strings, even for small values.
