### ISSUE TITLE
Add a @generated tag

### ISSUE THREAD

**Issue by tsloughter** [tomas-abrahamsson/gpb#233]
I've been trying to use elp, https://github.com/WhatsApp/erlang-language-platform, and when hitting perf issues I opened a ticket and learned they have an issue with these proto generated modules, https://github.com/WhatsApp/erlang-language-platform/issues/16#issuecomment-1952057946. I wouldn't expect you to accept having an eqwalizer specific attribute in each module, but the `@generated` tag in the docs could be useful in general?

**Comment by tomas-abrahamsson** [comment]
Hi, `@generated` is now included in the 4.21.1, so I'll be closing this ticket. Feel free to re-open or open a new if there should be anything more.
