### ISSUE TITLE
Does maps support is stable ?

### ISSUE THREAD

**Issue by yueyoum** [tomas-abrahamsson/gpb#40]
the new maps syntax is very convenient，

I wanna use gpb with the maps syntax.

So,  Does the maps support is stable ?

**Comment by tomas-abrahamsson** [comment]
Yes, generally, the maps is stable. Any upcoming changes will be option controlled.

I suppose you're referring to the section in the README about maps. The first issue, a, about non-present optional fields, being present or not in the map, is about to change as part of #29, but it will (for now) be an option to make gpb generate code that works that way. Later on, the default behaviour might change, but with suitable options to allow for a graceful transition period.

**Comment by tomas-abrahamsson** [comment]
Closing this since I've just pushed 3.18.0, containing the option for non-set optional fields to be omitted/non-present. In the process of doing that, I also updated the README to reflect that maps have pretty much settled.
