### ISSUE TITLE
Name resolution issue in gpb_parse.post_process_all_files/2

### ISSUE THREAD

**Issue by mmmries** [tomas-abrahamsson/gpb#47]
I have two simple proto files like this:

### import.proto
```protobuf
package chat;
import "imported.proto";
message WebsocketServerContainer {
  required string name = 1;
  optional authorization.Failure failure = 2;
}
```

### imported.proto
```protobuf
package authorization;
message Failure {
  optional uint32 status_code = 1;
  optional string reason = 2;
}
```

I then scan, parse and `gpb_parse:post_process_one_file/1` each of these messages individually. Then when I merge these together into a single list of defs I get a data structure like:

```erlang
[
  {package, [chat]},
  {import, "imported.proto"},
  {{msg, ['.', 'WebsocketServerContainer']},[
    {field, name, 1, undefined, string, required, []},
    {field, failure, 2, undefined, {ref, [authorization, '.', 'Failure']}, optional, []}
  ]},
  {package, [authorization]},
  {{msg, ['.', 'Failure']},[
    {field, status_code, 1, undefined, uint32, optional, []},
    {field, reason, 2, undefined, string, optional, []}]
  }
]
```

And when I pass that to `gpb_parse:post_process_all_files/2` I get back an error tuple like:

```erlang
{error,[
  {ref_to_undefined_msg_or_enum,{{
    ['.','WebsocketServerContainer'],failure},
    [authorization,'.','Failure']}}]}
```

I've also tried reversing the order of the defs so that `authorization.Failure` is passed in before it gets used, but that didn't work either. Am I missing a call somewhere?

**Comment by tomas-abrahamsson** [comment]
hm.. this looks like a bug in gpb, I will take a look at it.

**Comment by tomas-abrahamsson** [comment]
hm.. again :) If parsed with the option `use_packages`, I think it works the way you wants. (I forgot (again) about that option. Sorry for the earlier confusion)

**Comment by mmmries** [comment]
@tomas-abrahamsson thanks so much. Sorry for asking so many questions. I hope I can keep contributing make to the project to make up for it :smile:

**Comment by tomas-abrahamsson** [comment]
No problems at all! You're welcome!
