### ISSUE TITLE
Add support for syntax tag in .proto

### ISSUE THREAD

**Issue by lpgauth** [tomas-abrahamsson/gpb#52]
Hi,
I'm currently experimenting with protobuf 3.0. It would be nice to add support for `syntax = "proto2";` or `syntax = "proto3";` to specify a syntax version. This is part of protobuf 3.0-beta2.

Cheers,
LP

**Comment by tomas-abrahamsson** [comment]
Good point. Support for proto3 is still mostly to do, but in any case, the `syntax` statement ought to be supported, so I added support for it in 3.20.2. However, it only recognizes `"proto2"` so far. For now, specifying `"proto3"` will cause a parse time error, until more proto3 support is in place.

**Comment by lpgauth** [comment]
Perfect, thanks!
