### ISSUE TITLE
Encoding result is not the same with basho/erlang_protobuffs when having negative integers

### ISSUE THREAD

**Issue by goofansu** [tomas-abrahamsson/gpb#54]
* rebar.config

```
{plugins, [rebar3_gpb_plugin]}.

{provider_hooks, [{post, [
                          {compile, {protobuf, compile}},
                          {clean, {protobuf, clean}}
                         ]}
                 ]}.

{gpb_opts, [{module_name_suffix, "_pb"},
            {o_erl, "src/auto_gen/proto"},
            {o_hrl, "src/auto_gen/proto"},
            strings_as_binaries,
            type_specs,
            maps
           ]}.
```

* test.proto
```
message Test {
  required int32 result = 1;
}
```

* Outputs of gpb

```
test_pb:encode_msg(#{result => -1}, 'Test').

Outputs: <<8,255,255,255,255,15>>
```

* Outputs of erlang_protobuffs

```
import("test_pb.hrl").
list_to_binary(test_pb:encode_test(#test{result= -1})).

Outputs: <<8,255,255,255,255,255,255,255,255,255,1>>
```

It seems compressed for negative integers. Is there any option to control this result?

**Comment by goofansu** [comment]
I'm now using `sint32` to bypass this problem.

**Comment by tomas-abrahamsson** [comment]
Hmm.. It appears as if protobuffs encodes a 64 bit value of -1 even though the value is of type int32. I checked what the C++ code generated by Google's protobuf does (by generating nif code with gpb and C++ with protoc), and found this:
* it encodes -1 to <<8,255,255,255,255,255,255,255,255,255,1>>
* upon decoding, also <<8,255,255,255,255,15>> decodes to -1

In general, many values will decode to the same integer, also for positive values. For example given your proto definition, the following octet sequences all decode to `#{result => 1}` (by gpb as well as by Google's protobuf):
```erlang
  <<8,1>>
  <<8,129,0>>
  <<8,129,128,0>>
  <<8,129,128,128,0>>
```

What's your underlying goal with same binary representation from gpb and protobuffs? The decoded value, `-1`, is the same  for both octet sequences, I presume? (haven't checked with protobuffs)

**Comment by tomas-abrahamsson** [comment]
Forgot to say there's no option to gpb for generating code that encodes differently.

**Comment by goofansu** [comment]
We are developing a game using Erlang as backend and Lua as frontend.

In Lua, the encoding message is like basho/erlang_protobuffs, so it will
parse the negative integer in gpb to a very large integer, a wrong integer.

Tomas Abrahamsson <notifications@github.com>于2016年5月3日 周二下午6:19写道：

**Comment by tomas-abrahamsson** [comment]
Ah, I see. Then for interop reasons I'll look into changing gpb. It might be a few days though, I'm afraid.

**Comment by goofansu** [comment]
@tomas-abrahamsson Many thanks to you 🍺

**Comment by tomas-abrahamsson** [comment]
Hi, it was a quicker fix than I first anticipated, so I just pushed 3.20.3 which I believe fixes the issue. (added a unit test for it, as well)

**Comment by goofansu** [comment]
@tomas-abrahamsson Thanks, I tested it and it's ok.
