### ISSUE TITLE
Generated code & dialyzer warning

### ISSUE THREAD

**Issue by lukebakken** [tomas-abrahamsson/gpb#58]
Hi Tomas -

In basho/riak_pb#197, I have migrated to your `gpb` library (very easy to do!) and get several of these warnings when running `make dialyzer`:

```sh
riak.erl:3396: Expression produces a value of type ['ok'], but this value is unmatched
```

Here is the code that generates this warning:

```erlang
if is_list(F4) ->
   [v_msg_rpbcommithook(Elem, [precommit | Path])
    || Elem <- F4];
   true ->
   mk_type_error({invalid_list_of, {msg, rpbcommithook}},
         F4, Path)
end,
```

It is generated from the following field in the `RpbBucketProps` message in `src/riak.proto`:

```
repeated RpbCommitHook precommit = 4;
```

Basically, any `repeated` field will generate an `is_list()` call that triggers the dialyzer warning.

This is not a serious warning, and it is easy for me to ignore, but I thought I'd let you know. I am using OTP `R16B02` compiled from the `basho10` tag in [this repository](https://github.com/basho/otp).

**Comment by tomas-abrahamsson** [comment]
Managed to reproduce this with the dialyzer flag `-Wunmatched_returns`. I had not run with that flag previously. I'll look into it. (should be easy to fix, I hope)

**Comment by lukebakken** [comment]
Thanks, and like I said, not a serious issue at all :smile:

**Comment by tomas-abrahamsson** [comment]
I've just pushed 3.21.2, which fixes this. Even if not urgent, I figure the fix is better off pushed than idling locally, and there's no shortage of integers for version numbers, if need be :)
