### ISSUE TITLE
how to set value to oneof fields?

### ISSUE THREAD

**Issue by dcy** [tomas-abrahamsson/gpb#59]
Hi!
I have a protobuf:
```
message Chat {
	required ChatType type = 1;
	oneof  chat_oneof {
		CommonChat common_chat = 2;
		PrivateChat private_chat = 3;
	}
}

```
how to set value to ```chat_oneof```?

**Comment by tomas-abrahamsson** [comment]
Hi, that would be for example:
```erlang
    M = #'Chat'{type = ...,
                chat_oneof = {common_chat, #'CommonChat'{...}}}
```
So the `chat_oneof` is always a two-tuple, the oneof-field-name and its value.

**Comment by tomas-abrahamsson** [comment]
Hi again, forgot to say: All oneof fields are also always implicitly optional, so the example below is also be valid, and means no value is set for `chat_oneof`:
```erlang
    M = #'Chat'{type = ...,
                chat_oneof = undefined}
```

**Comment by dcy** [comment]
Thanks!

**Comment by tomas-abrahamsson** [comment]
You're welcome!
