### ISSUE TITLE
Ignore UTF-8 BOM

### ISSUE THREAD

**Issue by h4cc** [tomas-abrahamsson/gpb#67]
The Parser seems to fail for files with a UTF-8 BOM set:

```
** (CaseClauseError) no case clause matching: {:error, {1, :gpb_scan, {:illegal, [65279]}}, 1}
```

**Comment by tomas-abrahamsson** [comment]
Yes, BOMs are not expected. It seems Google protobuf accepts a BOM in 3.0.0-beta, but not in 2.6.1. I'll take a look.

**Comment by tomas-abrahamsson** [comment]
I just pushed 3.24.0, which skips over any UTF-8 BOMs. (hence closing this issue.)

(It also utf8-decodes the input .proto files, and utf8-encodes the generated files, but generally, this should be a nop in most cases. Only issue I can think of is non-ASCII in default values for strings, supposedly uncommon, but just for your information in any case)
