### ISSUE TITLE
Support for rpc option?

### ISSUE THREAD

**Issue by tony612** [tomas-abrahamsson/gpb#68]
service rpc defination supports [option](https://developers.google.com/protocol-buffers/docs/reference/proto2-spec#service_definition) like this:
```protobuf
service Greeter {
  // {} is support 
  rpc SayHello (HelloRequest) returns (HelloReply) {}
}
```
But only format without option is supported now:
```protobuf
service Greeter {
  // only `;` is supported now
  rpc SayHello (HelloRequest) returns (HelloReply);
}
```

**Comment by tomas-abrahamsson** [comment]
I've fixed the grammar for the rpc method options: just pushed 3.24.2, which should work better, I hope.

**Comment by tony612** [comment]
It works now. Thanks for your quick fix!
