### ISSUE TITLE
Forward compatibility for enums

### ISSUE THREAD

**Issue by ericmj** [tomas-abrahamsson/gpb#69]
Currently gpb crashes when decoding an unknown enum value. This breaks forward compatability for new enum values in the enum type. Would it be possible to add an option to have it not crash and decode to a value such as `{unknown, integer()}` or maybe just the integer value?

In my usecase I don't care about the actual value, I just want to have the decode not break on new values.

Another solution, to force users to handle the error case, would be to have enum values decode to `{ok, atom()} | {error, integer()}` when the option is enabled.

**Comment by tomas-abrahamsson** [comment]
I'd be inclined to decode it to just an integer, it's a type different from atom anyway, so I don't think a tuple is needed. I can't imagine anyone depending on the decoder currently crashing, so I think it would be ok to change the behaviour without introducing an option. For symmetry, it should probably be possible to encode integers as enums, too.  I'll look into it.

**Comment by ericmj** [comment]
That sounds good. Thanks for the quick answer!

**Comment by tomas-abrahamsson** [comment]
There's a 3.24.3 out now, which decodes unknown enums to integers.
