### ISSUE TITLE
'vsn' in gpb.app.src is of wrong type

### ISSUE THREAD

**Issue by Cloven** [tomas-abrahamsson/gpb#70]
in gpb.app.src, we see

{vsn, {cmd, "git describe --always --tags --match '[0-9]*.[0-9]*'"}},

but according to http://erlang.org/doc/man/app.html, the vsn key is of type string.

this breaks tools like relx that expect to be able to parse a version string when gpb is included as a dependency.

**Comment by tomas-abrahamsson** [comment]
The src/gpb.app.src is meant to be transformed, by the build tool -- rebar or make -- into ebin/gpb.app, which indeed has the format you linked to. In the resulting ebin/gpb.app, the version is not meant to be `{cmd,...}`, but instead the actual version. It's possible there's a bug in the build tool chain somewhere, how did you build?

**Comment by tomas-abrahamsson** [comment]
Hi, did this sort itself out, or is there still an issue?

**Comment by Cloven** [comment]
Sorry for not getting back. I upgraded to a later version of erlang.mk and
relx, and the problem seemed to resolve itself. Feel free to close and
thanks.

On Aug 7, 2016 3:34 PM, "Tomas Abrahamsson" <notifications@github.com>
wrote:

Hi, did this sort itself out, or is there still an issue?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/tomas-abrahamsson/gpb/issues/70#issuecomment-238112864>,
or mute the thread

**Comment by tomas-abrahamsson** [comment]
Ah, ok, no problems, good that it got sorted! (Closing)
