### ISSUE TITLE
Optional elements do not recognize implicit defaults

### ISSUE THREAD

**Issue by kolorahl** [tomas-abrahamsson/gpb#71]
When encoding a message, I noticed that I get an error when I have an optional element with no explicit default, but the protobuf specification defines implicit defaults for certain data types in this case that are not being recognized by `gpb`.

The full write-up can be found [here](https://developers.google.com/protocol-buffers/docs/proto3#default) for the proto3 spec and [here](https://developers.google.com/protocol-buffers/docs/proto#optional) for the proto2 spec. The short version is:

- Strings are empty string.
- Bytes are empty bytes.
- Bools are false.
- Numbers are zero.
- Enums are the first defined value, which must be zero.
- Messages are not set.
- Repeated fields are empty arrays.

I actually have a vague idea of how to implement this in the code so I'll try to submit a PR for this in the near future.

**Comment by tomas-abrahamsson** [comment]
> When encoding ... I get an error when I have an optional element with no explicit default

For proto3, this should work as in the link you refer to, and [there's a unit test for it](https://github.com/tomas-abrahamsson/gpb/blob/3.24.3/test/gpb_tests.erl#L743).  This test is actually executed for both the encoder in `gpb` and the code generated by `gpb_compile`.

For proto2, a related issue was #21, but then for decoding.

But I'm not sure I fully understand how you mean, I'd appreciate if you'd elaborate a bit: maps or records? perhaps an example?

**Comment by kolorahl** [comment]
Sorry, it was early when I wrote this up. Definitely allow me to go into further detail.

I have a message definition that looks something like this:

```
syntax="proto3";

message Msg {
  required string uid = 1;
  float field = 2;
}
```

If I build out a `Msg` record explicitly setting `uid` but not explicitly setting `field` then I will get an error during the encoding process.

However, thinking on it now, I might be generating the record poorly. I'm actually using this in Elixir, via [exprotobuf](https://github.com/bitwalker/exprotobuf), so `field` is being set to `nil` on record creation. When encoding the message I get an error [here](https://github.com/tomas-abrahamsson/gpb/blob/master/src/gpb.erl#L648). I couldn't see any place where an empty/undefined/nil value would be handled and a fallback default would be applied. I _did_ see [this check](https://github.com/tomas-abrahamsson/gpb/blob/master/src/gpb.erl#L543) for a default value, but it looks like it simply returns empty bytes in the case where the field is set to the default value.

The fix I was considering playing around with was going to be enhancing that check so that optional fields without a valid value (undefined/nil) would also return empty bytes so that decoding the message would allow it to follow the default-value rules. But, again, now that I'm thinking on it this may be a case where the record is generated improperly?

**Comment by tomas-abrahamsson** [comment]
No problems, I was thinking if the value is set to the atom `undefined`, then the default handling in `gpb` ought to have kicked in, since in proto3, all fields are (sort-of) optional (there is no `required`). But if the value is set to `nil`, then no default handling in `gpb` will kick in, and a crash is likely.

You could try verifying the message to check whether `field` has a valid value or not. Don't know if that is easy or not to do via `exprotobuf`, but if nothing else, it might be possible to set the option `{verify,always}` (or `-v always` if from the command line) to `gpb` when generating the proto code. Then it will generate code that always calls `verify_msg` internally inside `encode_msg`.

**Comment by kolorahl** [comment]
Yeah, I'll have to play around with the elixir library and get back to you.
I had thought nil values were an alias to the atom `undefined`, because I
don't recall an actual nil type/keyword in Erlang, but that seems unlikely
now.

On Aug 5, 2016 11:13 AM, "Tomas Abrahamsson" <notifications@github.com>
wrote:

No problems, I was thinking if the value is set to the atom undefined, then
the default handling in gpb ought to have kicked in, since in proto3, all
fields are (sort-of) optional (there is no required). But if the value is
set to nil, then no default handling in gpb will kick in, and a crash is
likely.

You could try verifying the message to check whether field has a valid
value or not. Don't know if that is easy or not to do via exprotobuf, but
if nothing else, it might be possible to set the option {verify,always} (or -v
always if from the command line) to gpb when generating the proto code.
Then it will generate code that always calls verify_msg internally inside
encode_msg.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/tomas-abrahamsson/gpb/issues/71#issuecomment-237923061>,
or mute the thread

**Comment by pcewing** [comment]
I experienced this too updating from proto2 to proto3 syntax; I was previously able to encode default messages but started encountering errors. I'm also using the *exprotobuf* package. I put together a basic repository [here][exproto] with an example to investigate. If you run the unit tests, the third test will fail with the error you described:
```
(stdlib) :unicode.characters_to_binary(:undefined)
       src/gpb.erl:627: :gpb.encode_value/3
       src/gpb.erl:568: :gpb.encode_field_value/4
       src/gpb.erl:506: :gpb.encode_2/4
       test/exproto_test.exs:23: (test)
```

I'm going to take a look at what *exprotobuf* is doing when it calls into `gpb:encode`.

[exproto]: <https://github.com/pcewing/exproto>

**Comment by tomas-abrahamsson** [comment]
Indeed, looks like bug in `gpb`, I'll look into it, thanks for reporting. Also, thanks for making that repository. and also for the README.md in that repo; it was very useful for me since I'm not very used to Elixir and its build process.

**Comment by kolorahl** [comment]
I'll be verbose in my debugging and thought process just in case anyone is interested, but the TL;DR is that I believe the parser is incorrectly setting the `occurrence` field in the new proto3 syntax.

I started by logging the following output from `gpb`. I put log lines in the `encode_field` functions for `required` and `optional` occurrence matches.

```
REQUIRED: Type = uint32, Value = 1470441926
REQUIRED: Type = float, Value = 180.12039
REQUIRED: Type = float, Value = -12.28349
REQUIRED: Type = float, Value = undefined
```

That confirms that exprotobuf is passing `undefined` for fields without an explicit value. **However** we can also see that all of my floats, which should all be _optional_, are actually entering the _required_ field flow. So to track down why the field was considered "required" I started at the beginning: with parsing the proto file. Thankfully that seemed to be the source of the bug.

I looked through the YRL file and found [this line](https://github.com/tomas-abrahamsson/gpb/blob/master/src/gpb_parse.yrl#L146). It seemed to be marking all fields without an explicit `occurrence` part as `required` when the default per the proto3 syntax spec should actually set it to `optional`. I changed those lines and re-ran my own code and found it to be working as expected.

As an aside, not sure how to create a unit test for this. Want me to figure it out and add it to the PR?

**Comment by pcewing** [comment]
@kolrahl I was literally typing up a post about that line in the *gpb_parse* file haha. That does seem to be the culprit. *exprotobuf* uses *gpb*'s parser so it makes sense that it would surface in that package.

**Comment by tomas-abrahamsson** [comment]
:) Agree with your analysis completely. Can't remember why I thought they should be required back then, but that's obviously wrong. There are two eunit tests for the gpb_parse that fails with the #72 in its current form, so I think that'll do for eunit tests.
```erlang
gpb_parse_tests: proto3_no_occurrence_test...*failed*
in function gpb_parse_tests:proto3_no_occurrence_test/0 (test/gpb_parse_tests.erl, line 615)
**error:{badmatch,[{proto3_msgs,[m1]},
           {syntax,"proto3"},
           {{msg,m1},
            [{field,f1,1,2,uint32,optional,[]},
             {field,f2,2,3,uint32,repeated,[packed]}]}]}
  output:<<"">>

gpb_parse_tests: proto3_sub_msgs_gets_occurrence_optional_test...*failed*
in function gpb_parse_tests:proto3_sub_msgs_gets_occurrence_optional_test/0 (test/gpb_parse_tests.erl, line 631)
**error:{badmatch,[{proto3_msgs,[m1,s1]},
           {syntax,"proto3"},
           {{msg,m1},
            [{field,f1,1,2,{msg,s1},optional,[]},
             {field,f2,2,3,{msg,s1},repeated,[packed]}]},
           {{msg,s1},[{field,f1,1,2,uint32,optional,[]}]}]}
  output:<<"">>
```
Also, I think the [call to `gpb_parse:make_proto3_submsg_fields_optional`](https://github.com/tomas-abrahamsson/gpb/blob/master/src/gpb_parse.yrl#L743) would not be needed any more, and that function would probably collapse away.

**Comment by tomas-abrahamsson** [comment]
Would you want to have a go at it, or else, I can take your PR in #72 and amend it with the above? Either way is fine with me

**Comment by tomas-abrahamsson** [comment]
If you don't have any objections within not too long, I'll go ahead and merge an amended #72 and push a new version (with a few more changes and fixes)

**Comment by kolorahl** [comment]
Sorry, I had accidentally run my own project's tests forgetting to run the tests directly in `gpb`. I also meant to get to this yesterday but life decided to interject.

I'm running the tests now, checking out those two errors you showed, and will submit an updated PR once everything passes.

**Comment by kolorahl** [comment]
I've updated the PR. And just as a reassurance, I didn't simply change `required` to `optional`; I did check out the message string and ensure that it was the expected behavior, which it is for the proto3 syntax. All 366 tests show green for me now.

**Comment by tomas-abrahamsson** [comment]
No problems, excellent! I'll merge it

**Comment by tomas-abrahamsson** [comment]
I just pushed 3.24.4, including this, so closing this ticket. Again, many thanks for the contribution! The 3.24.4 contain a few more issues, maybe one of interest for you, since you're using proto3, an encoding bug for repeated fields of type string, bytes and sub messages (found when cross-checking with Google's protobuf 3.0.0)
