### ISSUE TITLE
Record Names

### ISSUE THREAD

**Issue by tsloughter** [tomas-abrahamsson/gpb#73]
Is there a way to specify the record name for a message or to set a formatter besides suffix/prefix/lowercase?

Specifically I'd like to have the message `CamelCase` become the record `#camel_case{}` instead of `#camelcase{}`.

Digging around in the code this does not seem to be supported, would it be an acceptable contribution?

**Comment by tomas-abrahamsson** [comment]
It would certainly be acceptable, and you're right there currently does not exist something to provide this.

I'm thinking it could either be a `snake_case` option (or something) or an option to set a more general transformation function. For the snake_case alternative, I think it would not conflict with any existing option, if we would say it implies `msg_name_to_lower`. For a more general transformation option, one would have to consider interaction with other options (such as `msg_name_to_lower` and `msg_name_prefix`), perhaps the easiest would be to say this is an error and that the options are mutually exclusive. A `snake_case` option could easily also be a command line option, whereas a more general transform is not.

**Comment by tsloughter** [comment]
`snake_case` would be perfect. I'll look at adding that as well as fixing the bug I reported regarding `oneof`.

**Comment by tomas-abrahamsson** [comment]
Excellent!

**Comment by tomas-abrahamsson** [comment]
I merged your `msg_name_to_snake_case` option in #76 and pushed 3.25.0 (Closing this)
