### ISSUE TITLE
Google Protobufs 3 incompatibility

### ISSUE THREAD

**Issue by Cloven** [tomas-abrahamsson/gpb#78]
Given "msg.proto": 

syntax = "proto3";

message Payload {
  int32 seq = 1;
  bytes payload = 2;
};

message ServerMessage {
  int32 seen = 1;
  int32 ack = 2;
  repeated Payload payloads = 3;
};

gpb encodes 

{'ServerMessage',1,2,
                    [{'Payload',1,<<"derpyderp1">>},
                     {'Payload',2,<<"derpyderp2">>},
                     {'Payload',3,<<"derpyderp3">>},
                     {'Payload',4,<<"derpyderp4">>},
                     {'Payload',5,<<"derpyderp5">>}]}

to the 81 byte bin

<<8,1,16,2,26,75,14,8,1,18,10,100,101,114,112,121,100,101,114,112,49,14,8,
       2,18,10,100,101,114,112,121,100,101,114,112,50,14,8,3,18,10,100,101,114,
       112,121,100,101,114,112,51,14,8,4,18,10,100,101,114,112,121,100,101,114,
       112,52,14,8,5,18,10,100,101,114,112,121,100,101,114,112,53>>

and the protobuf3 generated C++ encoder generates the 84 byte bin

<<8,1,16,2,26,14,8,1,18,10,100,101,114,112,121,100,101,114,112,49,26,14,8,2,18,
  10,100,101,114,112,121,100,101,114,112,49,26,14,8,3,18,10,100,101,114,112,
  121,100,101,114,112,49,26,14,8,4,18,10,100,101,114,112,121,100,101,114,112,
  49,26,14,8,5,18,10,100,101,114,112,121,100,101,114,112,49>>

and gpb is able to decode its own bin, and protobuf3 is able to decode its own bin, but gpb crashes with an exception ("no function clause matching msg:skip_64_Payload(<<18,10,100,101,114,112,121>>,0,0,0,<<>>,undefined)") trying to decode protobuf3's bin, and protobuf3 does not recover the repeated Payload field from gpb's bin (the resulting payload field is []).

**Comment by tomas-abrahamsson** [comment]
I believe this bug was fixed in 3.24.4 of gpb. Which version are you on? 3.24.3 and earier versions were broken in this regard.

Technically, it was a bug handling repeated fields of type `string`, `bytes` and sub messages (and thus also of `map<_,_>` type fields). Fields are by default `packed`, except for these types. In 3.24.3 and earlier, gpb erroneously defaulted to `packed` for all types of fields, but this was fixed in 3.24.4.

**Comment by Cloven** [comment]
I think that was it.  I merged in the latest changes and the compatibility issue I saw went away.  I'll close this and will open up another issue if I encounter any incompatibility with 3.24.4+.  Thanks Tomas!
