### ISSUE TITLE
gpb_opts - additional documentation and examples...???

### ISSUE THREAD

**Issue by Keam** [tomas-abrahamsson/gpb#84]
Hi Tomas,

Is there any additional documentation or examples to better learn your plugin? I will admit I'm new to Erlang (3-4 months).  I've read through your source code but still trying to wrap my head around it. Specifically, I want to see how to use your plugin to decode  serialized protocol buffers attached as the binary payload of an HTTP POST request...with Content-Type set application/octet-stream. And to encode to serialized protocol buffer as the payload of an HTTP POST response with Content-Type set application/octet-stream.

I'm designing a module using cowboy_http behavior to handle HTTP request and responses and want to decode (handle) the serialized pb and encode (handle) responses to serialized pb. 

I hope this make sense,  any guidance will be appreciated.

Thank you!

**Comment by Keam** [comment]
Me again, 

First, thank you for all your hard work. 

Second, after reading your ``gpb_compile.erl`` specifically,


>  doc
> 
>  Compile a .proto file to a .erl file and to a .hrl file. 

>The File must not include path to the .proto file. Example: "SomeDefinitions.proto" is ok, while > >"/path/to/SomeDefinitions.proto" is not ok.
> 
> The .proto file is expected to be found in a directories specified by an ``{i,directory()}`` option. It is possible to specify ``{i,directory()}``  several times, they will be searched in the order specified. 



Do I need to manually create the directory ``mkdir -p``?  or does
```
{gpb_opts, [
    		{i, "../_build/proto_dir"},
    
    		{module_name_suffix, "_pb"},
    
    		{o_erl, "../_build/out_src"},
    
    		{o_hrl, "../_build/out_include"},
    
    		{strings_as_binaries, true},
    
    		type_specs]}.

```
create the directory by ``rebar3 compile`` ? I tried the ``rebar3 compile`` option and directories were not created. 

Sorry if this is real newbie questions.

**Comment by tomas-abrahamsson** [comment]
I think you're missing `rebar3 protobuf compile` before `rebar3 compile`.

I think this is actually more of a [rebar3_gpb_plugin](https://github.com/lrascao/rebar3_gpb_plugin) question than a `gpb` question, but here's some guidance.

I set up an example app, `mylib` using just `rebar3 new app`.

I had the following relevant lines in `rebar.config`:
```erlang
{erl_opts, [debug_info, {i, "./_build/default/plugins/gpb/include"}]}.
...
{gpb_opts, [{i, "src"},
            {o_hrl, "include"},
            {o_erl, "src"},
            {module_name_suffix, "_pb"},
            {strings_as_binaries, true},
            type_specs]}.
{provider_hooks, [
    {pre, [{compile, {protobuf, compile}},
           {clean, {protobuf, clean}}]}]}.
```
And this in `src/mylib_x.proto`:
```protobuf
message m {
  required uint32 f = 1;
}
```

I generated `mylib_x_pb.erl` and `mylib_x_pb.hrl` into the `_build/...` dir from `src/mylib_x.proto` using: `rebar3 protobuf compile` The `rebar3_gpb_plugin` compiles `.proto` files it finds in the directories from the `{i,Dir}` option(s), and internally prepends the dest build directory to any `o_erl` and `o_hrl` options. Directory creation is automatic.

Then I compiled these using `rebar3 compile`.

To use the generated code, I could call `mylib_x_pb:decode_msg(Bin,m)` where Bin is some http POSTed data I've got via cowboy. Decoding would give me an `#m{}`. Or I could call `Bin = mylib_x_pb:encode_msg(#m{f=4711})` to get me a binary I could send to cowboy for shipping over http.

Hope this is useful for you

**Comment by Keam** [comment]
Thank you Tomas, that worked. You were correct I was missing the `rebar3 protobuf compile` step. I check the directories and it appears all the proper files have been created.

To test, 

```
$ cd myapp
$ rebar3 shell 
1> myapp_pb:   
```

At this point, the decode or encode functions are not available. I understand your instructions but I'm I loading the myapp_pb incorrectly?

Thank you again for your help

**Comment by tomas-abrahamsson** [comment]
You might need to load the module into the shell before it can expand. For example `l(myapp_pb).` or `m(myapp_pb).` The former will load the module. The latter will print some info about it, and to do that, as a side-effect, it will first load the module.

**Comment by Keam** [comment]
Thank you again!

However, I did learned that using a hyphen `-` in the file name is a no no

This didn't work:
```
$ rebar3 shell
1> m(rtb-myapp_pb).
** exception error: an error occurred when evaluating an arithmetic expression
     in operator  -/2
        called as rtb - myapp_pb

```

This did work

```
rebar3 shell
1> m(rtb_pb).
Module: rtb_pb
MD5: 819507be6604e......
```

**Comment by tomas-abrahamsson** [comment]
Yes :) It is possible to have "funny" characters in module names (which are just atoms). You have to [quote the atoms, like this: `'rtb-myapp_pb'`](http://erlang.org/doc/reference_manual/data_types.html#id70857). But it is generally easier and more common to go with underscores instead of dashes.

**Comment by tomas-abrahamsson** [comment]
I take it your issue with gpb is solved, and we can close this? For general questions about Erlang itself, I thought I should hint about subscribing to the erlang-questions mailing list over at http://www.erlang.org/community/mailinglists

**Comment by Keam** [comment]
thanks!
