### ISSUE TITLE
Add option for major version compatability

### ISSUE THREAD

**Issue by ericmj** [tomas-abrahamsson/gpb#88]
I have an issue where I generate .erl files on OTP19 and then use them on OTP17. This causes issues with the dialyzer nowarn attributes that are generated.

A work around for me could be to instead always generate on the lowest OTP version I want to support but it would be nicer if it could be an option instead.

**Comment by tomas-abrahamsson** [comment]
Yes, I should think that ought to be doable to add an option for which major OTP version to target. I will look into it.

**Comment by tomas-abrahamsson** [comment]
In the just-pushed 3.26.0 release, there's a `{target_erlang_version,N}` option, to support your use case. (Closing)

**Comment by ericmj** [comment]
Thank you!

**Comment by tomas-abrahamsson** [comment]
You're welcome! It turned out to be useful also because I could unit-test some code paths that were otherwise difficult to reach.
