### ISSUE TITLE
when imported proto file changed, rebar3 compile will not recompile the proto, any ideas?

### ISSUE THREAD

**Issue by zhangr011** [tomas-abrahamsson/gpb#93]
<pre>
---- rebar.config ----
{provider_hooks, 
 [
  {pre, [{compile, {protobuf, compile}},
         {clean,   {protobuf, clean}}]}
 ]}.
</pre>
<pre>
---- pb_17.proto ----
syntax = "proto3";

package protobuf;
import "pb_common.proto";

...
</pre>
<pre>
---- pb_common.proto ----
syntax = "proto3";

package protobuf;

...
</pre>

when pb_common.proto changed, rebar3 compile will not compile pb_17.proto.

**Comment by tomas-abrahamsson** [comment]
Sorry, I don't know. This would be an issue for https://github.com/lrascao/rebar3_gpb_plugin which does the compilation.

**Comment by zhangr011** [comment]
thanks, i'll move this issue to https://github.com/lrascao/rebar3_gpb_plugin.

**Comment by tomas-abrahamsson** [comment]
Closing this issue here since it is continued over in lrascao/rebar3_gpb_plugin#30
