### ISSUE TITLE
import proto from another package, compile failed.

### ISSUE THREAD

**Issue by zhangr011** [tomas-abrahamsson/gpb#95]
when we use proto like this, the compile will not success, can u help me?
<pre>
package pb_commom;

message pbId32 {
        optional int32 id = 1;                          // 32位的id信息
}
</pre>
<pre>
package pb_9;
import "pb_common.proto";

//null
message pbnull {
        optional pb_common.pbId32 id = 1;
}
</pre>
got error like this:
<pre>
===> proto files found: ["/Users/zhangrong/repository/leshu/server_p05/subgit/p05_proto/pb_common.proto",
                                "/Users/zhangrong/repository/leshu/server_p05/subgit/p05_proto/pb_9.proto",
                                "/Users/zhangrong/repository/leshu/server_p05/subgit/p05_proto/pb_50.proto",
                                "/Users/zhangrong/repository/leshu/server_p05/subgit/p05_proto/pb_40.proto",
                                "/Users/zhangrong/repository/leshu/server_p05/subgit/p05_proto/pb_30.proto",
                                "/Users/zhangrong/repository/leshu/server_p05/subgit/p05_proto/pb_21.proto",
                                "/Users/zhangrong/repository/leshu/server_p05/subgit/p05_proto/pb_19.proto",
                                "/Users/zhangrong/repository/leshu/server_p05/subgit/p05_proto/pb_18.proto",
                                "/Users/zhangrong/repository/leshu/server_p05/subgit/p05_proto/pb_17.proto",
                                "/Users/zhangrong/repository/leshu/server_p05/subgit/p05_proto/pb_16.proto",
                                "/Users/zhangrong/repository/leshu/server_p05/subgit/p05_proto/pb_15.proto",
                                "/Users/zhangrong/repository/leshu/server_p05/subgit/p05_proto/pb_14.proto",
                                "/Users/zhangrong/repository/leshu/server_p05/subgit/p05_proto/pb_13.proto",
                                "/Users/zhangrong/repository/leshu/server_p05/subgit/p05_proto/pb_12.proto",
                                "/Users/zhangrong/repository/leshu/server_p05/subgit/p05_proto/pb_11.proto",
                                "/Users/zhangrong/repository/leshu/server_p05/subgit/p05_proto/pb_10.proto"]
===> compiling "/Users/zhangrong/repository/leshu/server_p05/subgit/p05_proto/pb_9.proto" to "/Users/zhangrong/repository/leshu/server_p05/_build/default/lib/server/src/protocol/pb_9_pb.erl"
===> opts: [{i,"./subgit/p05_proto"},
                   {module_name_suffix,"_pb"},
                   {o_erl,"/Users/zhangrong/repository/leshu/server_p05/_build/default/lib/server/src/protocol"},
                   {o_hrl,"/Users/zhangrong/repository/leshu/server_p05/_build/default/lib/server/include"},
                   {strings_as_binaries,false},
                   type_specs,
                   {i,"/Users/zhangrong/repository/leshu/server_p05/subgit/p05_proto"},
                   {i,"/Users/zhangrong/repository/leshu/server_p05/subgit/p05_proto"}]
in msg pbnull, field id: undefined reference  pb_common.pbId32

===> failed to compile /Users/zhangrong/repository/leshu/server_p05/subgit/p05_proto/pb_9.proto: in msg pbnull, field id: undefined reference  pb_common.pbId32
</pre>

**Comment by tomas-abrahamsson** [comment]
I think you need to set the `gpb` option `use_packages`

**Comment by zhangr011** [comment]
thanks, this is help for me.
