### ISSUE TITLE
"message" keyword cannot be used for a message name 

### ISSUE THREAD

**Issue by ionuthristodorescu** [tomas-abrahamsson/gpb#99]
I have the following : 

    message message {
      optional string first = 1;
      optional string last = 2;
    }

but when I compile I get : 

>>./bin/protoc-erl -I. test.proto
../test.proto:1: syntax error before: message

(if I change to "message message { ... }" to "message Message { ... }", then it works). 

This is a valid protocol buffer definition, could you fix it ? This is our top level protocol message and it's hard for us to change the name to top_message (for example). Thank you.

**Comment by tomas-abrahamsson** [comment]
I just pushed 3.26.6, which should fix this. The parser in gpb is a leex/yecc-based one, whereas I believe the protoc one is a recursive-descent one, so there are inherently some grammar limitations, but this one was easily fixable. Closing, just reopen should there be anything more to it.

**Comment by ionuthristodorescu** [comment]
THANK you, it works, just tested it. I was looking into the parser myself, but you were quicker.

**Comment by tomas-abrahamsson** [comment]
Thanks for feedback, good to hear!
